### ISSUE TITLE
adding a carousel for images on the property detail page

### ISSUE THREAD

**Issue by kcjod** [Soujanya2004/wanderlust-2024#10]
adding a carousel for images on the property detail page that allows users to swipe through multiple images and improve ui of property detail page

**Comment by krishkishore972** [comment]
hey i want to work on this issue assign me now

**Comment by Soujanya2004** [comment]
@krishkishore972 progress?

**Comment by shivanjalikarande** [comment]
@krishkishore972 are you working in this? If not, @Soujanya2004 could you please assign this issue to me?
I will create PR soon after assigning to me.

**Comment by Soujanya2004** [comment]
> @krishkishore972 are you working in this? If not, @Soujanya2004 could you please assign this issue to me? I will create PR soon after assigning to me.

you can work on it

**Comment by shivanjalikarande** [comment]
Okay, @Soujanya2004 could you please assign this issue to me. I will start working on it & will create PR soon.
