### ISSUE TITLE
[Bug]: Add responsiveness to whole website

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

make the website responsive to mobile view
(You can raise pr for every page ex: listing view page, home page, login/signup page)

### Expected behavior

make whole website responsive

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
I’m already working on adding customized pages to the footer quick links. Could you please assign this issue to me?
