### ISSUE TITLE
[Bug]: update navbar

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

add faq link

### Expected behavior

direct to faq section

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
assign it to me.

**Comment by garimabhayanaa** [comment]
can you assign me this task?
