### ISSUE TITLE
Improve Navbar UI and Functionality

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#11]
The current navbar can be enhanced to improve both user experience and aesthetics. Suggested improvements include:

Making the navbar responsive across all device sizes (mobile, tablet, desktop).
Enhancing the visual design (e.g., color scheme, hover effects, or animations).
Adding dropdown functionality for better organization of links.
Ensuring the links are accessible and user-friendly.

@Soujanya2004 

I'd like to work on improving the navbar UI and functionality for this project. Please assign this issue to me, and I'll start working on the enhancements.

**Comment by dipexplorer** [comment]
Could you please add the hackatoberfest and hacktoberfest-accepted label to this issue.

**Comment by geetanjalidubey9** [comment]
pls assign this task to me.

**Comment by Soujanya2004** [comment]
@geetanjalidubey9 this project is not under hactokerfest
