### ISSUE TITLE
[Feature Request]: Adding a feedback section

### ISSUE THREAD

**Issue by sinhaudita** [Soujanya2004/wanderlust-2024#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to implement a feedback section in the website so that the users could share their experience about using this website. Also the feedback submitted would be displayed on the site. 

### Use Case

To enhance the user activity of the site, this feature would be beneficial.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@sinhaudita there is a review section already and feedback means the same ryt
