### ISSUE TITLE
[Feature Request]: Add my profile page

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding profile page for users to view their signin infomation

### Use Case

better user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
Hi, I’d like to work on this issue, but I need clarification on whether the portfolio or profile page is already hosted, or if a new one needs to be created. Additionally, could you please specify where exactly this page should be added? Any guidance would be helpful. Thank you!

**Comment by Soujanya2004** [comment]
@dipexplorer the profile page doesn't exist now, as we click on the profile icon on the top right of navbar, I need it to redirect to a my profile page which displays their username, emailid , (we can add features like add profile pic later)

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
