### ISSUE TITLE
[Feature Request]: Mobile UI Improvements Needed

### ISSUE THREAD

**Issue by srishti023** [Soujanya2004/wanderlust-2024#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The mobile view has several issues that need addressing:

Search Bar: Not displaying properly, making it hard to access.
![Screenshot 2024-10-18 115657](https://github.com/user-attachments/assets/e2b54a37-1be4-4253-be42-199632a51f28)

Button Styling: Login and signup buttons need better visibility and styling.
Cross-Options on Forms:
Add "Sign Up" on the login page.
Add "Login" on the signup page.

![Screenshot 2024-10-18 115603](https://github.com/user-attachments/assets/e386ba0d-7931-4ea7-a11b-539db13c6325)

Progress Bar: Visibility issues on mobile screens, affecting functionality.

### Use Case

Implementing these features will greatly enhance the user experience by:

A visible search bar makes it easier for users to find content quickly.
 Well-styled login and signup buttons improve visibility and interaction.
Cross-options on forms streamline the user journey between login and signup.
 A clear progress bar helps users track their progress, reducing confusion.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
