### ISSUE TITLE
[Feature Request]: Adding Loading Icon

### ISSUE THREAD

**Issue by Bhum-ika** [Soujanya2004/wanderlust-2024#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding creative loading icon while website is loading

### Use Case

Will improve the user experience

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0d203007-3001-4015-a49a-6e1da63677a0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Bhum-ika** [comment]
Can i get a dummy mapbox token to proceed with this issue

**Comment by Soujanya2004** [comment]
@can you give the contact detail so that i can share

**Comment by Bhum-ika** [comment]
Sure, you can mail at sharmabhmi@gmail.com

**Comment by Soujanya2004** [comment]
@Bhum-ika u can check it

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.

**Comment by Bhum-ika** [comment]
![image](https://github.com/user-attachments/assets/9f3f085c-ddb3-4991-9993-9c5d4846ad44)

i am getting this

**Comment by Soujanya2004** [comment]
@Bhum-ika first pull the updated repo

**Comment by Bhum-ika** [comment]
I did no update. Kindly assign this issue to someone else

**Comment by shubhagarwal1** [comment]
hey @Soujanya2004 please assign me this task
