### ISSUE TITLE
[Feature Request]: Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Soujanya2004/wanderlust-2024#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description
I want to add a page to showcase all the contributors of this website .  @Soujanya2004 can you assign me this issue.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@T-Rahul-prabhu-38 make sure u add in new page for that don't add in the home page, and add page link in the footer

**Comment by T-Rahul-prabhu-38** [comment]
<img width="1457" alt="Screenshot 2024-10-18 at 4 44 57 PM" src="https://github.com/user-attachments/assets/fb42e4e9-1997-479e-8e68-56d2868606ce">
<img width="1326" alt="Screenshot 2024-10-18 at 4 45 03 PM" src="https://github.com/user-attachments/assets/608c2019-7e29-4512-860c-11386a962b82">

**Comment by Soujanya2004** [comment]
@T-Rahul-prabhu-38 got it, u can proceed
