### ISSUE TITLE
[Bug]: Problem in description field in 'Airbnb your home' form.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Here have three problems.**
1) In this form when you add description. This field supposed to be a 'Textarea' insted of normal 'Input'
Because description should be long many time.  So it's obvious to change it as textarea. 

2) The price, country & location can be fit in one row. Unnecessarily you make it in two row, For this it occupied bigger pace, Which is not supposed to be. Because the price, country, location  are small field in case of it's length. 

3) There should be a heading for this page. That supposed to be "Add your property details". Because in first what this form do the normal user did not understand. If there is no heading.

By this change the form enhance the UI & UX which is more important for user.

### Expected behavior

The description should be looks like this.
![image](https://github.com/user-attachments/assets/ac4128d4-1ed5-44b6-8f93-d94e53bc93da)

The price, country & location part should be looks like this:
![image](https://github.com/user-attachments/assets/7bbf4205-1b98-49cf-b7d1-58cf63aa5c9c)

### Add ScreenShots

Your current form looks like this
![image](https://github.com/user-attachments/assets/4b5dec93-b3ac-436f-97ba-69ad5fc19506)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana
