### ISSUE TITLE
[Feature Request]: Feature enhancement of the sign in & sign up section in navbar.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

For now the section where the Sign in & Sign up are displaying on navbar, It implement a logic that is the user logged in then show only 'log out' option.  If not then show 'Sign Up' & 'Sign In'

For now the format of it'd displaying style is too simple and not good at all.

Here i want to improve it's format. Like when logged in it display different avatar like 'Profile Image Avatar'  and when logged out it display different avatar.

### Use Case

I wan to wrap up all that stuff that i said above, like this -->

Uploading in.mp4…

Which is looking cool, more understandable for normal user, like modern website.

### Add ScreenShots

For now it's looks like this.  Which is not good
![image](https://github.com/user-attachments/assets/abd18420-cf2c-46e3-9bfe-903919c35caa)
![image](https://github.com/user-attachments/assets/b077cf55-e3e2-4f8f-9989-a3fbe6163dad)

Please assign me this task. I want to work on it. Please give high label for this as possible, It would be very appreaciated for me. Thank you. @S 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004   give me label for points please. as per guideline,

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
