### ISSUE TITLE
[Bug]: Problem in Delete, Edit, Log In, Sign In buttons style.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1)   The Edit, Delete buttons currently in small in size and also are outlined button which is not even properly visible in a flash.  Which is not good as a User.

Here is the problem:
![image](https://github.com/user-attachments/assets/efda0ac5-539b-468a-8ad3-b486b24d578f)

2)  The Log In, Sign Up buttons in Log in & Sign Up pages are not styled properly. It's not look like button anymore. Just apear a normal text.  Not looks like button in a flsha.

Here is the problem:
![image](https://github.com/user-attachments/assets/1dec8fce-0c4a-4c4d-8dc1-b0c7d94cf6f1)
![image](https://github.com/user-attachments/assets/29b3bcb0-79bf-46be-a286-65f9bc00a2ee)

### Expected behavior

1) Make this Edit' Delete button solid and little bit bigger to make look it more visually appealing.
Nearly looks like this little bit 
![image](https://github.com/user-attachments/assets/6d8cb37c-5796-4a97-b668-d0d52e21bf5d)

2) Also same thing need to do with the 'Log In & Sign In buton

### Add ScreenShots

@Soujanya2004 

Please Assign me this ISSUE, I want to work on it. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by hemanthijjurouthu** [comment]
With your permission, I would like to take the opportunity to address and resolve this issue. I believe working on it would provide me with a valuable learning experience, and I'm confident that my contributions could bring meaningful improvements. I would be grateful for your approval
