### ISSUE TITLE
[Bug]: Redesign Navbar

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the navbar now looks clumsy and nav links are not arranged properly

### Expected behavior

Display all the nav links properly with enough spacing and add hover effects

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
Hi, I’d like to work on this issue. Could you please clarify the exact improvements you want for the navbar? Specifically:

How would you prefer the nav links to be arranged?

Once I have more details, I can start making the necessary changes. Please assign this issue to me. Thank you!

**Comment by Suvadip-sana** [comment]
@Soujanya2004    I would like to work on this issue.

**Comment by Soujanya2004** [comment]
@dipexplorer 
![navbar-blur](https://github.com/user-attachments/assets/f6922a51-4b9f-41bd-9301-c67597e99f30)

 similar to this, add explore as a button. let the plane icon remain in the same place

**Comment by Soujanya2004** [comment]
@Suvadip-sana since @dipexplorer has asked first i will be assigning it , please find other issues or raise issue if needed

**Comment by hemanthijjurouthu** [comment]
"Ma'am, I would like to take the initiative to work on this issue. Could you kindly assign it to me? I’m confident that I can contribute effectively and would appreciate the opportunity."

**Comment by Suvadip-sana** [comment]
@Soujanya2004 Is this ISSUE assigned to me? Please let me know.

**Comment by Soujanya2004** [comment]
@dipexplorer will you be working on this or can I assign to others

**Comment by dipexplorer** [comment]
yes i will raise the soon
