### ISSUE TITLE
[Bug]: Implement Dark Mode for /about Page

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, the /about page does not support proper dark mode.

### Expected behavior

When toggled, the /about page should display a proper dark background with light text.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
