### ISSUE TITLE
[Bug]: Implement Dark Mode for /terms Page

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The /terms page remains in light mode despite dark mode being enabled.

### Expected behavior

The /terms page should switch to a dark theme with appropriate CSS, JS adjustments.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
