### ISSUE TITLE
[Bug]: Implement Dark Mode for New Listing Page

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 The New Listing page does not support dark mode and remains in light mode.

### Expected behavior

When toggled, the New Listing page should display a dark background with light text and input fields.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
