### ISSUE TITLE
[Bug]: Implement Dark Mode for Show Listing Page

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Show Listing page does not change to dark mode when enabled.

### Expected behavior

The Show Listing page should switch to a dark theme with appropriate color adjustments for displayed content and UI elements.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.

**Comment by Soujanya2004** [comment]
@dipexplorer can u add a toggle button in the homepage and every other page works based on the selected theme

**Comment by Soujanya2004** [comment]
> I would like to contribute on this as i am good full stack developer. please assign me that issue.

please find other issues or raise an issue if required, this is first come basis

**Comment by dipexplorer** [comment]
> @dipexplorer can u add a toggle button in the homepage and every other page works based on the selected theme

Hi @Soujanya2004,

I’ve already implemented the dark mode toggle button, and it is currently positioned in the right corner of the page, visible on every page, including the homepage. I placed it there because the navbar already contains several links, and I wanted to keep the design clean.

Could you clarify if you're asking for a different placement or a change in its behavior? If you'd like the button to be in a different location or have other adjustments, please let me know!

**Comment by Soujanya2004** [comment]
> > @dipexplorer can u add a toggle button in the homepage and every other page works based on the selected theme
> 
> Hi @Soujanya2004,
> 
> I’ve already implemented the dark mode toggle button, and it is currently positioned in the right corner of the page, visible on every page, including the homepage. I placed it there because the navbar already contains several links, and I wanted to keep the design clean.
> 
> Could you clarify if you're asking for a different placement or a change in its behavior? If you'd like the button to be in a different location or have other adjustments, please let me know!

yeh i just checked that now, its better in the position it is
