### ISSUE TITLE
[Feature Request]: The whole website font is not professional.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/5b0cd09d-0ae3-42e6-a1c6-68dde9026b93)
![image](https://github.com/user-attachments/assets/cd060a89-640c-4023-ac6b-ea858cb98e6f)

The all over websites fonts is not professional that other modern website have.  So make it more advance I think the whole website fonts modification is needed.

### Use Case

I think this type of professional websites fonts looks it more visually appealing for sure.
![image](https://github.com/user-attachments/assets/8aa8153f-c22a-4fd5-9c18-73e7348103a4)

@Soujanya2004  Please assign me this task. It's supposed to be need improvment.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.

**Comment by hemanthijjurouthu** [comment]
With your permission, I would like to take the opportunity to address and resolve this issue. I believe working on it would provide me with a valuable learning experience, and I'm confident that my contributions could bring meaningful improvements. I would be grateful for your approval
