### ISSUE TITLE
[Feature Request]: Animation on accordion.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In home page the accordion is not looking authentic because of it doesn't have any dropdown animation.  It's happening too fast not even recognizable that when it open actually. Problem as you seen on recording.

### Use Case

Here it should be an dropdown animation. Which make it more visually appealing and authentic.

### Add ScreenShots

https://github.com/user-attachments/assets/2d4794dc-e7da-49a1-98b9-fbe87d8deee1

@Soujanya2004  Please assign me this task. I want to work on this ISSUE.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by hemanthijjurouthu** [comment]
With your permission, I would like to take the opportunity to address and resolve this issue. I believe working on it would provide me with a valuable learning experience, and I'm confident that my contributions could bring meaningful improvements. I would be grateful for your approval
