### ISSUE TITLE
[Bug]: Proper implementation of text color

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot (211)](https://github.com/user-attachments/assets/053fdccf-8e9c-45be-a625-6cd1450d5481)
![Screenshot (212)](https://github.com/user-attachments/assets/df90b879-b521-4452-9ba4-3cdf154057cf)
'Project statics' and listing name - text in the dark mode is not visible,

### Expected behavior

 just change to text-color: white so that text will be visible even in dark mode

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004 please assign me this task

**Comment by hemanthijjurouthu** [comment]
With your permission, I would like to take the opportunity to address and resolve this issue. I believe working on it would provide me with a valuable learning experience, and I'm confident that my contributions could bring meaningful improvements. I would be grateful for your approval

**Comment by Soujanya2004** [comment]
@hemanthijjurouthu thanks for the interest but assignment works on first come first basis, you can your raise issues or try other issues

**Comment by Soujanya2004** [comment]
@Suvadip-sana can you change contributors cards to light red in dark theme, i will add level2

**Comment by Suvadip-sana** [comment]
@Soujanya2004   Ok got it.

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
Provide me the color that you want.

**Comment by Soujanya2004** [comment]
@Suvadip-sana use same colour as the plane icon in navbar
