### ISSUE TITLE
[Bug]: change toggle icon

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

toggle switch remains same even on changing to dark theme

### Expected behavior

change the toggle icon to sun when in dark mode and moon when in light mode

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004 assign me this.
