### ISSUE TITLE
[Bug]: Persist Dark Mode Preference Across Pages

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, the dark mode toggle works, but when navigating to different pages, the dark mode setting is reset to light mode. 

### Expected behavior

The expected behavior is for the dark mode setting to persist across all pages so the user experience remains consistent.

### Suggested Fix:
- Use `localStorage` to store the user's theme preference.
- On page load, retrieve the stored theme and apply it accordingly.
- Update the toggle button's state based on the stored theme.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

Please assign this issue to me.

**Comment by Soujanya2004** [comment]
@dipexplorer the toggle can be changed in any page, and it should be applied to every page
