### ISSUE TITLE
Improve the UI for the "Leave a review" section and show page with responsiveness

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#15]
The current "Leave a review" section and show,ejs needs a UI improvement to enhance user experience. Suggested improvements include:

Improve the UI for the show individual listing section.
adding proper responsiveness to the listing section.
fixing the alignment of map section.

I'd like to work on the review UI section with hover effects. Please assign this issue to me.

**Comment by Soujanya2004** [comment]
@dipexplorer please make a pr and then raise an issue, so that I can close similar issues
