### ISSUE TITLE
Improve UI for Review showing section

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#16]
The current review showing section looks unattractive. This issue aims to enhance its UI by:

Adjusting the design to make it visually appealing.
Adding padding and margin for better spacing.
Improving color contrast and font styles for better readability.

Could you please assign this issue to me and add the hacktoberfest and other lables.

**Comment by Soujanya2004** [comment]
@dipexplorer the project is not under hactoberfest , as of now it is for GSSoC-extd

**Comment by dipexplorer** [comment]
Could you please assign this issue to me I like to contribute to it.
