### ISSUE TITLE
[Feature Request]: Want to add 'Go to top' button for each page. ✨

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Your website maximum pages are long, need to scroll manually. And it taks time, sometime annoing too.  Mainly for the `Home Page` & the `Contributors Page` is annoying to scroll up from footer section in bottom. So I want to implement a common 'Back to top' button just like the attached video.

### Use Case

It help user to scroll up the page in one click.

### Benefits

@Soujanya2004 

please give this ISSUE atleast `label-2` or `label-3` . Because in your website all pages are not too long to have the 'back to top' button. If i add then it effect the UX directly.
So there is need JS logic to hide this for small pages. Also I assured you for it's responsiveness and it's not static, comes with cool animation.  hope you understood. @Soujanya2004  Thank You.

### Add ScreenShots

https://github.com/user-attachments/assets/853717ad-f2f1-47b8-8fa6-e5d552c02960

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004 

Why you closed this?  Please elaborate?

**Comment by Soujanya2004** [comment]
> @Soujanya2004
> 
> Why you closed this? Please elaborate?

I am really sorry for the confusion, I closed by mistake
