### ISSUE TITLE
 [Feature Request]: Add Tags Attribute to `listingSchema` to Support Filter Card Functionality

### ISSUE THREAD

**Issue by Dev-Rishav** [Soujanya2004/wanderlust-2024#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is currently a card filter section that displays different tags for visiting places, such as surfing, beach, and farms. However, the existing schema does not include an attribute to specify which tags are associated with each place.

I propose adding a `tags` attribute to the existing `listingSchema`. This can be accomplished by:

- Adding a `tags` attribute to the `listingSchema` to define different tags.
- Updating all existing entries to include their relevant tags.
- Implementing the necessary CRUD operations to handle tag assignment and retrieval for objects in the `listingSchema` views.

### Use Case

- Each place should be associated with one or more tags in the database schema.
- The tags should be retrievable and display properly alongside their respective places.

### Add ScreenShots

Current Schema:
![Screenshot from 2024-10-20 23-13-59](https://github.com/user-attachments/assets/b5deca93-e4b5-4621-8f12-40301a09e171)

View:
![Screenshot from 2024-10-20 20-17-58](https://github.com/user-attachments/assets/e297d7a7-9a62-445a-8f1e-654fa270a8a2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [x] I have starred the repository

**Comment by Soujanya2004** [comment]
@Dev-Rishav here you go

**Comment by Soujanya2004** [comment]
@Dev-Rishav any progress

**Comment by Dev-Rishav** [comment]
@Soujanya2004 currently working on it!

**Comment by Soujanya2004** [comment]
@Dev-Rishav

**Comment by Meetpidev** [comment]
@Soujanya2004 this is still an issue ??
