### ISSUE TITLE
[Bug]: Profile Picture Upload Not Functional

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Upload Profile pic" button exists, but the functionality to actually upload and update the profile image is not working.

### Expected behavior

 Users should be able to upload and update their profile picture, with the updated image reflected on their profile page using JS functionality.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@dipexplorer will you be able to do or should i assign it to others

**Comment by dipexplorer** [comment]
I will raise the PR soon.
