### ISSUE TITLE
Enhance Responsive Design 

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#17]
The current UI collapses on smaller screen sizes, resulting in a poor user experience and disrupting the overall UI. 
This issue aims to:

Ensure text remains legible and visually appealing across all device sizes.
Adjust font sizes and styles to prevent collapse.
Optimize spacing and alignment to maintain a clean layout.

Could you please assign this issue to me and add the hacktoberfest and other labels.

**Comment by Sonalgupta2005** [comment]
@dipexplorer Could I help you with this enhancement in the project or u need any help related to this?

**Comment by Sonalgupta2005** [comment]
if yes, please assign me this issue with the particular labels.

**Comment by Soujanya2004** [comment]
@Sonalgupta2005 it's already assigned, you can raise new issues
