### ISSUE TITLE
ADD a Dedicate Github Contributors page to the website 

### ISSUE THREAD

**Issue by shubhagarwal1** [Soujanya2004/wanderlust-2024#173]

**Comment by Soujanya2004** [comment]
@shubhagarwal1 it's already implemented

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 it's already implemented

Hey @Soujanya2004 may i know anything specific you are planning to implement, i would be a great to make contribution here.

**Comment by Soujanya2004** [comment]
@shubhagarwal1 you can raise an issue and work on the feature you wish to implement
