### ISSUE TITLE
[Bug]: Alignment Issues

### ISSUE THREAD

**Issue by sayiamarora** [Soujanya2004/wanderlust-2024#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

To fix the issue with the alignment in the page

### Expected behavior

To fix the alignment of the divs .

### Add ScreenShots

![error](https://github.com/user-attachments/assets/d31520e3-1860-4adc-aa8d-a4562af7c1a6)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Abhijeet14d** [comment]
Assign this to me I can work on it
