### ISSUE TITLE
[Bug]: two edit options

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

'edit your details' and 'edit profile' option are displayed which is for same purpose

### Expected behavior

remove one edit option and its funtionality 

### Add ScreenShots

![Screenshot (225)](https://github.com/user-attachments/assets/42db728e-32bb-403e-8b5a-eb5c027ca63f)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
assign it to me
