### ISSUE TITLE
[Feature Request]: Add Scroll-to-top button

### ISSUE THREAD

**Issue by SurajPrakash24** [Soujanya2004/wanderlust-2024#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It will be very efficient for user to directly go to top of page with just one click. This button will be fixed on the page so while scrolling, it will not move.

-Implement a "Scroll to Top" button that appears when the user scrolls down more than 200 pixels.
-Button will smoothly scroll the page back to the top when clicked.
-Add responsive styling for better user experience

@Soujanya2004  plz assign this issue to me under gssoc-ext level 2 and hacktoberfest-accepted

### Use Case

It will be very efficient for user to directly go to top of page with just one click.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@SurajPrakash24   This ISSUE is already raised #160

**Comment by SurajPrakash24** [comment]
@Suvadip-sana Okay
