### ISSUE TITLE
[Feature Request]: Redesigning & adding links to toggle between login and signup page

### ISSUE THREAD

**Issue by SurajPrakash24** [Soujanya2004/wanderlust-2024#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to redesign the login and signup page as it is very basics and also not user friendly. The buttons are not visible properly and there is no link to go to signup page from login and vice-versa.

@Soujanya2004 Plz assign this issue to me under gssoc-ext level 2.

### Use Case

It will enhance the user efficiency with great visuals and proper links.

### Add ScreenShots

I want make good UI and add link like this.
![Don’t have an account! Signup](https://github.com/user-attachments/assets/f114b887-2436-4e0b-adae-c858485de591)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ambrishgoswami** [comment]
I have searched the  issues in login button

**Comment by SurajPrakash24** [comment]
@Soujanya2004 This issue is not only related to change the button color But also adding links and making the Form more user efficient.

**Comment by Soujanya2004** [comment]
@SurajPrakash24 you can raise another issue, i will assign you
