### ISSUE TITLE
[Feature Request]: Add Contact Us form

### ISSUE THREAD

**Issue by SurajPrakash24** [Soujanya2004/wanderlust-2024#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add Contact Us form where user can type their name & message and submit the form. The message along with name will be automatically emailed to the support@wanderlust.com email or any other provided email. I am also going to make the email feature using nodemailer. 

@Soujanya2004 Plz assign this issue to me under gssoc-ext level 3 

### Use Case

It would be more efficient for user to not open email and then send message, They can directly type and send their message to us on this platform itself.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@SurajPrakash24 progress?

**Comment by SurajPrakash24** [comment]
I will update asap

**Comment by NK-Works** [comment]
@Soujanya2004 I can work on it if you want...
U can assign me

**Comment by NK-Works** [comment]
Will be done by tomorrow
