### ISSUE TITLE
[Bug]: text not visible

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

'Add your property details' text is not visible in dark mode

### Expected behavior

change color to white

### Add ScreenShots

![Screenshot (228)](https://github.com/user-attachments/assets/e43a397c-5a38-41a1-a965-e07e689ede3c)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Suvadip-sana 
Assign me. 
I would like to fix this.
