### ISSUE TITLE
[Feature Request]: add booking functionality

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

user will be able to book site
options include no. of nights spending, check-in date and time etc.
no other user can book the same site while the user stay is not completed.

### Use Case

feature addition of website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@raj-adi00 just booking

**Comment by NK-Works** [comment]
@Soujanya2004 I can work on it as there is no PR as of yet....
U can assign me

**Comment by Soujanya2004** [comment]
@NK-Works when can i expect it to be done

**Comment by Soujanya2004** [comment]
@Meetpidev

**Comment by NK-Works** [comment]
By tomorrow it will be done

**Comment by Soujanya2004** [comment]
@NK-Works one of the features depends on this so please make it quick

**Comment by NK-Works** [comment]
working on it.... will make the pr by midnight
