### ISSUE TITLE
[Bug]: Duplicate Login/Signup and View Profile Icons in Navbar

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

fixing the search bar alignment for small screen size.

### Expected behavior

The search bar is aligned properly and behaves consistently across different pages and screen sizes.

### Add ScreenShots!

![24 10 2024_18 59 41_REC](https://github.com/user-attachments/assets/8bb5cbb2-f273-4347-8938-c3e3bc5a0965)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@dipexplorer  this is mistakenly commit. I already resolve it in my last pr👍
