### ISSUE TITLE
Hosting this website on vercel so that contributers can easily contribute to it by live preview

### ISSUE THREAD

**Issue by tarunkumar2005** [Soujanya2004/wanderlust-2024#21]
Hosting this website on vercel so that contributers can easily contribute to it by live preview

**Comment by tarunkumar2005** [comment]
@Soujanya2004 Can i host it on my vercel account or you will provide me account to host it that way you will be able to manage the website right with your credentials and account.

**Comment by Soujanya2004** [comment]
I will provide you my account by tomorrow, please wait @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@Soujanya2004 Provide it on the linkedin dm okay that will be safer. here is my linkedin profile link :- https://www.linkedin.com/in/tarunkumar8278

**Comment by Soujanya2004** [comment]
Sure 👍 @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@Soujanya2004 you haven't shared the credentials??? Or i have another option also i can host it on my account but i would need the repo access so it is best you provide yours account.
