### ISSUE TITLE
[Bug]: change login/signup hover color

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hover color is not matching the theme of website

### Expected behavior

change grey color to red (same as hover color on 'Airbnb your home' in navbar)

### Add ScreenShots

![Screenshot (3)](https://github.com/user-attachments/assets/53829823-1fab-4c6e-9f77-6053419dec44)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
assign it to me.

**Comment by rajnish032** [comment]
assign to me
