### ISSUE TITLE
[Feature Request]: Want to redesign the whole index page

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently your index page the all listing display format is not perfect. Means here unnecessary padding and spacing  are there. Also the description section is not properly displayed. It is the main reason that the extra space is accuird by the lists. 
Also the `Show more` button is not looking good also it's not appear for all lists, So it's not looking good at all.
![abc](https://github.com/user-attachments/assets/24b18486-de5d-43c3-983e-3936c3f9d518)

### Use Case

It supposed to be look like this
![image](https://github.com/user-attachments/assets/832ea2fc-0e46-4bd4-b8bc-8491bd20de04)

Where description is not displayed. Because there is `show in deails` option so i don't think there is any nee dto display the description in front page. By doing this it also look more visually appealing

### Add ScreenShots

https://github.com/user-attachments/assets/1112b4ef-5955-418f-ad85-edbd8fc99c46

@Soujanya2004  Please assign me this task. I want to work on this.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana make sure its responsive instead of raising another issue for adding responsiveness
