### ISSUE TITLE
[Bug]: Problem in Sign-in page password view toggle button

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you seen in the video the eye icon is not changing while toggling to view the password. Also in darkmode the Icon stepped down into second row and also it's not visible.  Which is a problem as a normal user.

### Expected behavior

It supposed to be toggle between normal eye icon and cross eye icon. Other wise it's bit difficult  to understand. Also there is a problem in dark mode. The toggle icon going in to second row. Which is a problem .

### Add ScreenShots

https://github.com/user-attachments/assets/4577c720-1dff-4012-924c-6adf7bbdf1a6

@Soujanya2004   Please assign me this ISSUE. I want to fix this ISSUE.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana since it about changing icon and placing eye toggle in the same row, i will assign it level2 (and same issue raised for login also with level2)

**Comment by Suvadip-sana** [comment]
Ok ok it's fine. I told exactly same. 
@Soujanya2004  please add points label
