### ISSUE TITLE
[Bug]: Upload profile pic not working

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you can see in the attached video the profile pic upload functionality is not working. 
And also the default avatar i mage have water mark. Which not good for a website. And also not appealing.

### Expected behavior

Honestly in my opinion. I don't think in this type of website there is any need to give the profile pic upload feature.
If it's obvious to have this feature. Then it should be given when the user register in this platform right? Other wise after create the account there is no reason to give this feature. Also it would take extra cloudinary storage along with property images. Which is allowed to be store more than one. So definitely it take more extra sorage. Which is supposed to be over storaging problem some time.

So for now I think need to terminate the Upload profile pic feature. And here only present a default avatar. Though there is edit profile option, which is ultimate necessary thing also it functional properly.   

I change the current default avatar if you assign me this. Because it has water mark.

### Or 
It is need to complete this feature completly functional. And allow user to input there profile pic when they register in this platform.

Tel me what is your opinion in this topic

### Add ScreenShots

https://github.com/user-attachments/assets/cac30cb9-4aaa-4ca6-b184-cf64f866c2a1

![image](https://github.com/user-attachments/assets/92aaba7e-59e1-45d8-aead-fb23322335c0)

@Soujanya2004  Please assign me if you think it's an  ISSUE.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana i do have plans of implementing more features like booking, for that having profile webpage will be necessary so let this feature be.
i tried to upload the picture and its working perfectly fine by the way.

**Comment by Soujanya2004** [comment]
@Suvadip-sana you can raise separate issue for changing avatar

**Comment by Suvadip-sana** [comment]
In this I built the upload profile pic feature right? By only this route `/profile/upload`?
@Soujanya2004

**Comment by Soujanya2004** [comment]
@Suvadip-sana i didnt get you

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
Means I want to say that. In this ISSUE I only built the profile pic upload functionality?  Or anything else?

**Comment by Soujanya2004** [comment]
@Suvadip-sana yeh yeh, make sure user is able to upload a pic from local storege

**Comment by Soujanya2004** [comment]
@Suvadip-sana try to store pic in base64 format instead of cloudinary

**Comment by Suvadip-sana** [comment]
base64 format means? I don't understand.
Is other cloud storage like cloudinary or what?

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
If it is other than cloudinary then provide me the official documentation.

**Comment by Soujanya2004** [comment]
@Suvadip-sana i meant in mongodb convert image into base64 format

**Comment by Soujanya2004** [comment]
@Suvadip-sana you can use cloudinary if that's difficult, i do not have any documentation so just use cloud no issues

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
Ok i think. I am able to do it. But take time. I don't think it complete with in 3 days , Oct 30 th. There also another issues in your project. 
But I will try

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Ok Ok fine..

I try my best with in dead line.

Other wise I would live to work in this ISSUE. In separate time.

**Comment by Soujanya2004** [comment]
@Suvadip-sana sure, great to hear that

**Comment by Soujanya2004** [comment]
> @Soujanya2004 Ok i think. I am able to do it. But take time. I don't think it complete with in 3 days , Oct 30 th. There also another issues in your project. But I will try

just try to priorities this issue bcz rest all are level1

**Comment by Suvadip-sana** [comment]
> > @Soujanya2004 Ok i think. I am able to do it. But take time. I don't think it complete with in 3 days , Oct 30 th. There also another issues in your project. But I will try
> 
> just try to priorities this issue bcz rest all are level1

@Soujanya2004   yeh Sure.

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
I am troubling to implement with base64 
I do it with cloudinary. 
Create PR by tonight
