### ISSUE TITLE
no hover effect on navbar tags

### ISSUE THREAD

**Issue by geetanjalidubey9** [Soujanya2004/wanderlust-2024#25]
I saw the website and when i clicked on login and signup there was no hover effect visible

**Comment by geetanjalidubey9** [comment]
can i work on it

**Comment by SatyamTiwari069** [comment]
Add labels and please assign me the task as for gssoc24 extd

**Comment by AshleshPrabhu** [comment]
hey can i contribute to this issue? is the issue still unsolved?

**Comment by Soujanya2004** [comment]
it is solved already 
thank you
