### ISSUE TITLE
[Bug]: ⚠️ Urgent attention needed⚠️

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Your current changes on code base lead several causes of server failure. 
Not even connect with database initially. It crash when try to run the server.

After fixing the problem with database  connectivity from myself. Several pages/route are not working which was working well before. Shown that 'Page does not exist' error.

### Expected behavior

I think Some one try to restructure your codebase. 
Create router concept into this. I think this lead this ISUUE/ Crashes.

This changes is not deployed yet in your Deployment. That's why it is still working without crash. But after `Sync fork`  my local server completely crash

### Add ScreenShots

@Soujanya2004 
Please check then deploy. 
I am unable to do my work with my raised ISSUE.  Please check last PR marge based on `Code formatting` or something else related to this. If that is the case of the ISSUE. Then discard that PR, otherwise format the code in right way.

Please verify it.
@Suj

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
The edit profile functionality completely out. Not even render the profile edit form.
It's completely functional before this PR #244 
After this PR my PR is only for frontend. So I think my changes not cause this ISSUE.

Please check it. You should verify each commit after marging the PR. Otherwise this type of mejor server crases occur.

**Comment by Soujanya2004** [comment]
@Suvadip-sana I will fix it

**Comment by Soujanya2004** [comment]
@Suvadip-sana check now.

**Comment by Suvadip-sana** [comment]
@Soujanya2004   Ok cool!
Close this ISSUE
