### ISSUE TITLE
[Bug]: "Sign up", "Log in" & "Profile edit"  form are not responsive.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you can seen in the screenshots. This three form are not responsive.
Looking bad in small device.

### Expected behavior

I want to add this page responsiveness.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d206a3ab-172c-4061-911d-9635ad68eabf)
![image](https://github.com/user-attachments/assets/e810c0e1-8757-4985-b1b8-9747e5e9ce0a)
![image](https://github.com/user-attachments/assets/c0c3c00b-082e-4a44-812e-4d0eca7d65bc)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana for responsiveness max I can give level 2 
Just raise another issue for profile edit page

**Comment by Suvadip-sana** [comment]
Ok got it @Soujanya2004

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
I thought for 3 it supposed to be 'label-3'. That's why I am telling. 
Ok I raised another ISSU. No worries.
