### ISSUE TITLE
[Feature Request]: ContactUs page with backend

### ISSUE THREAD

**Issue by harshbhar0629** [Soujanya2004/wanderlust-2024#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is no contactus page there is no way to connect with user i want to implement contact us page with backend functionality using nodemailer. 

### Use Case

It increases the attraction of user towards wanderlust. 

### Benefits

User can directly interact with you via mail which is also a professional way to connect. 

User can directly ask any query with you. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
i will review pr and change the label, no worries @harshbhar0629

**Comment by harshbhar0629** [comment]
Ok sure..I will create PR today..

**Comment by harshbhar0629** [comment]
@Soujanya2004 Mapbox sdk error how we can access map token?? please suggest steps..
Otherwise i have same project which is Airbnb i can implement contact.ejs and show functionality to you and after i raised PR and you will merge because everything is same that's why i'm asking to you.

**Comment by Soujanya2004** [comment]
@harshbhar0629 send me ur contact info i will send u map token

**Comment by harshbhar0629** [comment]
8869826279
