### ISSUE TITLE
IMPORTANT : Encrypt Passwords Before Storing Them

### ISSUE THREAD

**Issue by iamsohelx** [Soujanya2004/wanderlust-2024#28]
## Description
Hey @Soujanya2004 In your website you are directly storing users password without encrypting it first.
This would an serious issue because users data is not secure.
anyone can see their passwords.

## Screenshot
![Hash8](https://github.com/user-attachments/assets/bab52b5d-8433-48b1-a2b1-df159e9b973c)

## Solution 
I can fix this issue by encrypting the password before storing it in database.
using Bcrypt, it will make your platform more secure.

**Comment by iamsohelx** [comment]
Hey @Soujanya2004 Where is your .env file i am getting an error while seting up the project on my laptop
![errr](https://github.com/user-attachments/assets/69157e70-5a34-4488-b5b5-1c9556532a38)

**Comment by Soujanya2004** [comment]
@iamsohelx I will fix it by today , please wait

**Comment by iamsohelx** [comment]
> @iamsohelx I will fix it by today , please wait

Okay. Please let me know

**Comment by Soujanya2004** [comment]
@iamsohelx progress?

**Comment by NK-Works** [comment]
@Soujanya2004 I can work on it can you assign me?

**Comment by harshbhar0629** [comment]
Please assign to me
