### ISSUE TITLE
[Feature Request]:  Add "View Reviews" Option on Individual Listings with Backend Support

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Each individual listing should have a "View Reviews" option, allowing users to read reviews specific to that listing. This feature will require backend support to fetch and display reviews associated with each listing.

### Use Case

Expected Behavior:

Add a "View Reviews" button on each listing card.
When clicked, this should open a section or modal displaying all reviews for that specific listing.
Integrate with the backend to retrieve and display reviews from the database.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@dipexplorer but user can now read reviews as they scroll down ryt

**Comment by dipexplorer** [comment]
@Soujanya2004 ,
i was talking about the manage listing page on admin side.
