### ISSUE TITLE
Adding Smooth and cool animation On buttons

### ISSUE THREAD

**Issue by iamsohelx** [Soujanya2004/wanderlust-2024#29]
## Description
Hey @Soujanya2004 In your website the buttons are very normal, we can add cool and transition on it making it look more appealing and making the user experience even smoother.
## Screenshot 
![hoverBtn](https://github.com/user-attachments/assets/7aa21a80-b68a-4b9e-a078-edba3af8cdba)

## Similar to This or as you want 

https://github.com/user-attachments/assets/07921c0a-4558-4459-b288-4abe4b9c5a42

**Comment by iamsohelx** [comment]
Hey @Soujanya2004 Could you please assign this task to me, I wanted to work on this. please.

**Comment by SatyamTiwari069** [comment]
Add labels and please assign me the task as for gssoc24 extd

**Comment by hemanthijjurouthu** [comment]
"Ma'am, I would like to take the initiative to work on this issue. Could you kindly assign it to me? I’m confident that I can contribute effectively and would appreciate the opportunity."
