### ISSUE TITLE
[Feature Request]: Add stargazers timeline

### ISSUE THREAD

**Issue by yashksaini-coder** [Soujanya2004/wanderlust-2024#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

My feature is to add an exported stargzers time line that will be used to showcase the timeline of all the contributors who starred your repo 

### Use Case

To engage with the contributors and provide more better engagement with them.

### Benefits

This will enhance the overall engagement of the contributors, who wants to contribute, and drive them to work more,

### Add ScreenShots

The end result would be an animated gif exported using my own project

https://github.com/user-attachments/assets/0dfadd5d-ea4e-43cc-a977-ce67021336f1

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@yashksaini-coder there is already contributor's webpage in our website, so i wouldn't require this

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder there is already contributor's webpage in our website, so i wouldn't require this

This is not for contributor's but for the stargazer who took interest in your project it is a great way of showing positive feedback, 


Also it is in the correct timeline order so ca be showcased once the project reach a milestone. Let me work on it just assign level 1 if you think it's not that big feat 

@Soujanya2004

**Comment by Soujanya2004** [comment]
@yashksaini-coder got it, u can work on that

**Comment by yashksaini-coder** [comment]
thanks

**Comment by yashksaini-coder** [comment]
@Soujanya2004 can you review the PR #325 I raised to fix this issue, only then can I start working on the #321 issue, as the problem is with the contributor.js file missing so proper contributions data is not fetched.
