### ISSUE TITLE
[Feature Request]: Add Chatbot Feature to Enhance User Experience

### ISSUE THREAD

**Issue by amanver45** [Soujanya2004/wanderlust-2024#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add chatbot integration to website

### Use Case

chatbot

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Assign it to me. It's been one week without response.

**Comment by Soujanya2004** [comment]
@amanver45 no work done after a week of assigning is considered invalid so assigning others
