### ISSUE TITLE
[Feature Request]: Structured Contact Us page.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently your contact us form does not have any normal mode or darkmode feature.   
Also it is not responsive in small screen not even in large screen. Also add unnecessary horizontal scrollbar. Which is not supposed to be. Also it's not match the color pallet of your website.

### Use Case

- I redesign whole page along with it's normal mode and dark mode implementation.
- Make it responsive for all screen.
- Remove the horizontal scroller from this page.

### As you can seen in this video

https://github.com/user-attachments/assets/dd9976bd-86e2-49bc-9621-07c0b8f0c111

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana you can work on the responsiveness of the page, @harshbhar0629 will modify the colors
