### ISSUE TITLE
[Feature Request]: Want to add a feed back form.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

For this web platform there should be a `Feedback form` where user can submit there feedback about this platform, like experience, information, accability etc.

### Use Case

I add a 5 star along with name and comment based feedback  form, Which I attached in footer. After clicking on that button a pop up opened at the middle of the screen. visitor can able to left there opinion. After that It display a greeting. Just like attached video.

It helps to improve the platform more better.

### Add ScreenShots

https://github.com/user-attachments/assets/fea23dac-db0a-45ad-b382-f24e696eadd3

https://github.com/user-attachments/assets/6245c3fa-1b89-4889-9b4f-b095507e3330

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana and where will all the feedback be displayed

**Comment by Suvadip-sana** [comment]
You tell me that. 
I thought for now it's only display in alert format. After that I add it's full backend functionality. Where I built a new mongo db model / route, then in a new page called 'feedback' where all the feedback display in grid card format.. 

@Soujanya2004 let me know what you think about. For now I built it's front end along with functionality of vanilla JS.

**Comment by Soujanya2004** [comment]
@Suvadip-sana i thought of adding a mail id and send the response to Gmail
yeah u can work on frontend for now
add this in homepage after faq section for now

**Comment by Soujanya2004** [comment]
@Suvadip-sana yeh that's nice actually, you can raise issue and work on it

**Comment by Suvadip-sana** [comment]
@Soujanya2004   yaa. thanks.  Currently I complete rest of the other ISSUE that I raised here. Hope this related all ISSUE will be assigned to me.

**Comment by Soujanya2004** [comment]
@Suvadip-sana sure
