### ISSUE TITLE
[Feature Request]: Want to add a default loader

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a default loader of this platform.    This loader is shown each page if server take time to send response.

### Use Case

When the backend take time for any request or response this loader display. Which looks good and fair when the server delayed something.  It can be displayed in every page of your site where needed.

### Add ScreenShots

https://github.com/user-attachments/assets/28bb8769-fdc6-4342-91a8-42eeedb0c9fc

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana make sure the loader is any animation related to travel, like a plane or a map 
left to ur creativity

**Comment by Suvadip-sana** [comment]
https://github.com/user-attachments/assets/ecf1b016-22b4-4ecf-915e-e065ea5acd9b


https://github.com/user-attachments/assets/f5baa537-f35b-431f-a389-5f2a668bb758


@Soujanya2004   Which one you love o implement as a default preloader for your website. It's  show untill your website is not load completly. For now your website have loader that only shown particular timeout only.

**Comment by Soujanya2004** [comment]
@Suvadip-sana the secon one is good actually
try to change color to match website theme

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Okkkk. Got it.
