### ISSUE TITLE
[Bug]: 404 error in the website

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Website is not loaded or page not found for every page because of improper routes implementation 

### Expected behavior

fix it by checking the backend

### Add ScreenShots

![Screenshot (243)](https://github.com/user-attachments/assets/ff127a3c-d7d1-4651-96b3-331469bfe8c0)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
@Soujanya2004 ,
Assign it to me, I am currently working on issues.

**Comment by Suvadip-sana** [comment]
@dipexplorer  Could you please create PR for this as soon as possible? Because it cause to stop the other modification.
Otherwise I already figure out the problem and solve it by my own, make PR?

@dipexplorer  Please give this ISSUE priority first,

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Please give it a attention. It cause the whole website shut down.

**Comment by Soujanya2004** [comment]
@Suvadip-sana since @dipexplorer is already working on it let him do it
just wait for today

**Comment by Suvadip-sana** [comment]
> > @dipexplorer Could you please create PR for this as soon as possible? Because it cause to stop the other modification. Otherwise I already figure out the problem and solve it by my own, make PR?
> > @dipexplorer Please give this ISSUE priority first,
> 
> i raise the PR soon

Cool
