### ISSUE TITLE
Enhancement in  Search box 

### ISSUE THREAD

**Issue by mr-rishikesh** [Soujanya2004/wanderlust-2024#31]
Hii @Soujanya2004 , if we see the search box then it look like a basic  search box the border radius not perfectly taken and box shadow . could you assign so that I can change some css code.

**Comment by Asjdnnc** [comment]
Hi @Soujanya2004, i wish to enhance the search bar by adding the search for name and country options to search the listing  from the database. i have already did this in my project
Assign me this task to add this feature
