### ISSUE TITLE
[Bug]: multiple images cannot be uploaded

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

user is not able to upload multiple images
after uploading 1 image another image upload option is not available
if we try to upload another image previous uploaded img is replaced

### Expected behavior

add multiple images uploading functionality
after uploading 1 image give option to add another image 

### Add ScreenShots

![Screenshot (244)](https://github.com/user-attachments/assets/2a0dccd9-287f-4540-81b2-75ee5eeb5939)
![Screenshot (245)](https://github.com/user-attachments/assets/82d15b93-8584-465c-9bca-3f8f4a50d9e5)
though it is written 'you can upload multiple images' as soon as we select a image there is no option to add another image

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
Assign it to me with labels.
