### ISSUE TITLE
[Bug]: App crashed totally

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to delete my own review. The app totally crashed.   You can verify it by your own.

### Expected behavior

For this it not supposed to be crashed. Because it's my own review. I should be allowed to delete my own review, this is the normal flow.

I currently when working on other ISSUE. Suddenly discover this problem. It need the whole `review` controller format and debugging, manual testing. Also some middleware issue in `isAuthor` this middleware mainly.   **So give it a fair points label.**

@Soujanya2004  You can check the problem. Then Please assign it to me!

### Add ScreenShots

https://github.com/user-attachments/assets/c6035d1d-f6a4-4ee7-b93d-94fe28e66338

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana i will review the pr and add necessary labels later
