### ISSUE TITLE
[Feature Request]: Existing List image delete feature in edit form.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In list edit form there is a option to upload new list image. But there is no way to delete existing image only.
I means that suppose user only want to delete one image from their list. Every time there may be no need to upload new image.

Sometime it is need to delete one or two image from list, because it is an multiple image upload system. So this delete feature should be there.

### Use Case

I add a checkbox for each image in edit form, where images are previewed that are already available for that list.

When user go to there list edit form, if they checked the box then submit the form, only that image will be deleted form database.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a23666a5-b57d-429d-97f3-d02116b90d96)

Under that preview images I attached a checkbox for each image.

@Soujanya2004  Please assign it to me.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana did u get the feature where user can upload multiple images
