### ISSUE TITLE
[Bug]: Deployment Link Not Working

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Page not found error in live link..

### Expected behavior

It should be deployed perfectly..

### Add ScreenShots
![image](https://github.com/user-attachments/assets/715deae9-9834-446d-bdec-b06692bb5b25)

### On which device are you experiencing this bug?
All The Devices.. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev can you priorities this and complete asap 
If u need any credentials then feel free to ask 
Just mention ur contact info along with it

**Comment by Meetpidev** [comment]
@Soujanya2004 Have you deployed it before ? if yes then is it working at that time ??

**Comment by Meetpidev** [comment]
@Soujanya2004 MapBox is paid.. if you used paid then requested to give me.. so i can deploy it..

**Comment by Meetpidev** [comment]
@Soujanya2004 Your link is working.. just see your README.md fil where you added link https://wanderlust-2024-tkqf.onrender.com/listing .. its worked.. then why you added different link ? of vercel ?

**Comment by Meetpidev** [comment]
@Soujanya2004 In the worked link there is a problem that is .. when we click on view details its show not found error... but when we create our list and then click on view details then its working fine...

**Comment by Soujanya2004** [comment]
> @Soujanya2004 Your link is working.. just see your README.md fil where you added link https://wanderlust-2024-tkqf.onrender.com/listing .. its worked.. then why you added different link ? of vercel ?

i have deployed on render, but for the sake of gssoc i wanted to deploy on vercel , bcc it will be easy to review pr ryt

**Comment by Soujanya2004** [comment]
> @Soujanya2004 In the worked link there is a problem that is .. when we click on view details its show not found error... but when we create our list and then click on view details then its working fine...

yeh we are working on that bug, no worries

**Comment by Meetpidev** [comment]
@Soujanya2004 sO CAN I DEPLOY IT IN VERCEL ? I MEAN BACKEND WILL BE DEPLOYED IN RENDER BUT FRONTEND WILL DEPLOY IN VERCEL

**Comment by Soujanya2004** [comment]
@Meetpidev sure work on it

**Comment by Meetpidev** [comment]
@Soujanya2004 MAP Is paid .. so what can i use instend of it ?

**Comment by Soujanya2004** [comment]
> @Soujanya2004 MAPBOX Is paid .. so what can i use instend of it ? and if i used other api or something then it maybe not working..

i will send u in linkedin check

**Comment by Soujanya2004** [comment]
@Meetpidev can you accept invite

**Comment by Meetpidev** [comment]
> @Meetpidev can you accept invite

Please read msg that i sent you.. that is help me to solve it

**Comment by Meetpidev** [comment]
@Soujanya2004 add current ip address into your DB.. add 0.0.0.0 so that i can access it..

**Comment by Soujanya2004** [comment]
@Meetpidev i have edited it already
