### ISSUE TITLE
[Bug]: Contributor javascript missing

### ISSUE THREAD

**Issue by yashksaini-coder** [Soujanya2004/wanderlust-2024#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The total no. of contributions is not properly showing

### Expected behavior

The contributors total number should be displayed there

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5933ac0a-6406-458d-aaa5-4d4c70bf4362)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by yashksaini-coder** [comment]
@Soujanya2004 can you assign me this issue

**Comment by yashksaini-coder** [comment]
@Soujanya2004 can I get level 2 as no JS script is present

**Comment by Soujanya2004** [comment]
@yashksaini-coder I will review pr and change the label no worries
