### ISSUE TITLE
[Bug]: show listings page not working 

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/user-attachments/assets/58850d70-75cb-4652-98ea-eff6e4e7c9c8

### Expected behavior

Solved the bug

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
@Soujanya2004 ,
Assign it to me. I am working on issues right now.

**Comment by dipexplorer** [comment]
@Soujanya2004 ,

Could u add level 3 here because significant changes are have to done in the backend to view the individual listing properly, even if the owner of the listing not stored in database( mainly local system when we added dummy data).
