### ISSUE TITLE
[Bug]: 404: NOT_FOUND

### ISSUE THREAD

**Issue by AaryaShrivaastava** [Soujanya2004/wanderlust-2024#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I tried accessing the project's website via the link provided, but it led to a 404 Not Found error. The link I attempted to visit is https://wanderlust-2024.vercel.app/ . It seems the page no longer exists or the URL has changed. Please check and update the link to ensure the site or documentation is accessible. Let me know if there’s any other information I can provide to help resolve this.

### Expected behavior

I expected the link to direct me to the project’s official website (or relevant documentation) where I could access resources or information about the project. The page should load correctly without returning a 404 error, allowing users to view the content as intended.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f26a2a78-6125-4094-9c93-16306f566157)

### On which device are you experiencing this bug?

Chrome, Windows, Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@AaryaShrivaastava check the link in readme file its working

**Comment by Soujanya2004** [comment]
@AaryaShrivaastava we are working on that also

> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> I tried accessing the project's website via the link provided, but it led to a 404 Not Found error. The link I attempted to visit is https://wanderlust-2024.vercel.app/ . It seems the page no longer exists or the URL has changed. Please check and update the link to ensure the site or documentation is accessible. Let me know if there’s any other information I can provide to help resolve this.
> 
> ### Expected behavior
> I expected the link to direct me to the project’s official website (or relevant documentation) where I could access resources or information about the project. The page should load correctly without returning a 404 error, allowing users to view the content as intended.
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/173633036/382334416-f26a2a78-6125-4094-9c93-16306f566157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MjQ2NjMsIm5iZiI6MTczMDUyNDM2MywicGF0aCI6Ii8xNzM2MzMwMzYvMzgyMzM0NDE2LWYyNmEyYTc4LTYxMjUtNDA5NC05YzkzLTE2MzA2ZjU2NjE1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNTEyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWEwNmQ5NmVhNjg1ZTRhNmZhNzNiNGM3NDJlNmI4MjU3ODg2YTJmYzgwNjIwNjFjNThlMWE2YmVmNGY0Mzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A6JPgguo49rbvLlxv5l-M7xc1xQXERPdlslg2SA96kw)
> 
> ### On which device are you experiencing this bug?
> Chrome, Windows, Android
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

working on that as well
