### ISSUE TITLE
[Feature Request]: add like the listing feature

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

user should be able to like any listing 
the like icon should be placed on each listing in both show listing (detail view of listing) and view listing (homepage) pages.

### Use Case

to specify popularity of any listing

### Add ScreenShots

on the top right corner of each listing there should be like icon/ heart icon
![Screenshot (247)](https://github.com/user-attachments/assets/955661bb-eb96-4fce-ab0d-28f34b4c2b1c)
![Screenshot (248)](https://github.com/user-attachments/assets/4bc07fe9-6cef-426f-8817-b3d66e74ff2d)
bottom right of each listing

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by yashksaini-coder** [comment]
assign this issue to me @Soujanya2004 I would like to work on this

**Comment by Soujanya2004** [comment]
@harshbhar0629

**Comment by Meetpidev** [comment]
@Soujanya2004 please close it as completed..
