### ISSUE TITLE
[Bug]: Show Listing Page Rendering 500 Error

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to view an individual listing page at /listing/:id, the website returns a 500 Internal Server Error.

### Expected behavior

The individual listing page should render correctly, displaying all relevant information about the listing, including the owner's username.

### Add ScreenShots

Uploading 02.11.2024_11.23.02_REC.mp4…

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@dipexplorer refer #322 
i have assigned you the issue also

**Comment by dipexplorer** [comment]
oh sorry
