### ISSUE TITLE
[Bug]: Home Tag In Navbar

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

 there should be option of it.. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7bb3367d-1d3c-4e47-ba4e-6f6379ef0891)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 I know but that is logo..  that plane and "explore" is consider as logo .. there should be separate option of HOME.. and the ttle 'airbnp ur home' its redirect to add listing.. that is wrong.. it should be titled as HOME.. and if we login with admin id then only show option of ad listing...

**Comment by Meetpidev** [comment]
Hope you understand what im trying to say

**Comment by Soujanya2004** [comment]
@Meetpidev got it, you can work on it
