### ISSUE TITLE
[Feature Request]: What type of listing is ?

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

By adding what type of listing is added, after that we can easly extrect that listing by type...

### Benefits

we can easly extrect that listing by type... by doing this that open place below navbar is working...

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 you said that you hold the PR that i sent... then why you merged PR that the same feature as this ??...
no worries.. You can close it...

**Comment by Meetpidev** [comment]
@Soujanya2004 what can i improve in tags? please tell me.. or you can close this issue..

**Comment by Soujanya2004** [comment]
@Meetpidev i guess its proper now so i will just close the issue
and there are many opened issues assigned to u please make sure u raise pr
