### ISSUE TITLE
improving design of login and sign up page

### ISSUE THREAD

**Issue by usha-here** [Soujanya2004/wanderlust-2024#34]
@Soujanya2004 
![image](https://github.com/user-attachments/assets/f63d6b19-c3a1-460e-b7d1-70b40e0f558a)
Good evening, 
I would like to enhance the design of login and sign up page , so if you could please assign this issue to me with gssoc-ext and hacktoberfest-accepted issue , it would be really great.
Thank you

**Comment by usha-here** [comment]
@Soujanya2004  Can you also add hacktoberfest-accepted label

**Comment by Soujanya2004** [comment]
This repo is not under hactokerfest  @usha-here

**Comment by SatyamTiwari069** [comment]
Add labels and please assign me the task as for gssoc24 extd

**Comment by sambangiadharsh** [comment]
Could I have your permission to work on fixing this issue? I believe it will be a great learning experience for me, and I’m confident that I can make valuable improvements
