### ISSUE TITLE
[Bug]: adding proper page for edit  listing  on listing page rendered from admin's dashboard

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Right now, their are no proper links or routes to direct to the proper page or form  for edit button.

### Expected behavior

When user click on the edit button proper page will be render to edit the listing  for the individual listings.

### Add ScreenShots

![Screenshot (237)](https://github.com/user-attachments/assets/a03e7909-b5d8-43df-9fa6-c122d56c92c2)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@dipexplorer can you give progress of #275 changes which i had mentioned

**Comment by dipexplorer** [comment]
> @dipexplorer can you give progress of #275 changes which i had mentioned

@Soujanya2004
I am working on that functionality, focusing on the environment variable check in admin.js to enhance security. Now I am raising an issue for that and also raised the PR shortly.

**Comment by Soujanya2004** [comment]
@dipexplorer sure, i will give you username password and email which has to be admin credentials
