### ISSUE TITLE
[Bug]: Adding Security to the Admin Setup

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding security to the Admin's functionality and prevent unauthorized access before executing the admin setup logic.

### Expected behavior

Prevents unauthorized users from running the admin setup logic.
Ensures only authorized personnel with the correct environment configuration can access the admin setup.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@dipexplorer how do i access admin setup now

**Comment by Soujanya2004** [comment]
it is showing error so

**Comment by dipexplorer** [comment]
@Soujanya2004,

Currently, no changes have been made to admin.js. To securely set up the admin credentials, I’m proposing a method where we can use an environment variable (e.g., SETUP_ADMIN) to control when the admin setup logic should run. This would prevent unauthorized users from running admin.js directly.

For now, you can still run admin.js as usual to access the admin setup. If there’s an error, could you provide more details on it? I can help troubleshoot based on that.

**Comment by Soujanya2004** [comment]
> @Soujanya2004,
> 
> Currently, no changes have been made to admin.js. To securely set up the admin credentials, I’m proposing a method where we can use an environment variable (e.g., SETUP_ADMIN) to control when the admin setup logic should run. This would prevent unauthorized users from running admin.js directly.
> 
> For now, you can still run admin.js as usual to access the admin setup. If there’s an error, could you provide more details on it? I can help troubleshoot based on that.

okkk got it
can you tell the steps to access admin page now
one of the contributors wanted it

**Comment by dipexplorer** [comment]
> > @Soujanya2004,
> > Currently, no changes have been made to admin.js. To securely set up the admin credentials, I’m proposing a method where we can use an environment variable (e.g., SETUP_ADMIN) to control when the admin setup logic should run. This would prevent unauthorized users from running admin.js directly.
> > For now, you can still run admin.js as usual to access the admin setup. If there’s an error, could you provide more details on it? I can help troubleshoot based on that.
> 
> okkk got it can you tell the steps to access admin page now one of the contributors wanted it, there was err in the password

@Soujanya2004 ,

Steps:
1. Directly run the admin.js (node admin.js)
2. Once the file run successfully, it will output this:
- Deleting existing admin user...
- Existing admin user deleted.
- New admin user created successfully!
 3.stop the admin.js and run node app.js
- Add visiting http://localhost:8080/admin/dashboard

**Comment by Soujanya2004** [comment]
@dipexplorer can i get you linkedin id

**Comment by dipexplorer** [comment]
> @dipexplorer can i get you linkedin id

@Soujanya2004,

Here’s my LinkedIn—
https://www.linkedin.com/in/dip-jyoti22/
It’s still a bit of work in progress to make it shine, so just ignore any rough edges 😄, but excited  to connect with you.

**Comment by Soujanya2004** [comment]
@dipexplorer already shining with ur work 😄

**Comment by dipexplorer** [comment]
> @dipexplorer already shining with ur work in github 😄

@Soujanya2004

Thank you—that means a lot! 😊
I’d  like to discuss the updates—would you prefer I share them here, or should I send them over on LinkedIn?

**Comment by Soujanya2004** [comment]
@dipexplorer better if its on linkedin

**Comment by Soujanya2004** [comment]
> > > @Soujanya2004,
> > > Currently, no changes have been made to admin.js. To securely set up the admin credentials, I’m proposing a method where we can use an environment variable (e.g., SETUP_ADMIN) to control when the admin setup logic should run. This would prevent unauthorized users from running admin.js directly.
> > > For now, you can still run admin.js as usual to access the admin setup. If there’s an error, could you provide more details on it? I can help troubleshoot based on that.
> > 
> > 
> > okkk got it can you tell the steps to access admin page now one of the contributors wanted it, there was err in the password
> 
> @Soujanya2004 ,
> 
> Steps:
> 
> 1. Directly run the admin.js (node admin.js)
> 2. Once the file run successfully, it will output this:
> 
> * Deleting existing admin user...
> * Existing admin user deleted.
> * New admin user created successfully!
>   3.stop the admin.js and run node app.js
> * Add visiting http://localhost:8080/admin/dashboard

![Screenshot (258)](https://github.com/user-attachments/assets/a4c51732-0907-47a6-861d-b868d985732b)

**Comment by Soujanya2004** [comment]
@dipexplorer can you look into its, everything worked but its showing access denied at end

**Comment by dipexplorer** [comment]
> @dipexplorer can you look into its, everything worked but its showing access denied at end
This might be you are not logged in as admin but still want to access the admin dashboard.
