### ISSUE TITLE
[Feature Request]: Feedback backend.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Assign it to me for Feedback backend.

### Use Case

The all my approach and implementation I discussed in that ISSUE #305  

I add this feedback schema along with `Joi` validation.

### Add ScreenShots

@Soujanya2004   Please assign it  to me under `label-3`. I want to implement this.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004    One clarification should visitor allow to delete their feedback? 
Or they only add the feedback. Rest functionality like delete operation and what to show, this permission only allow for admin? Because this approach follows in modern website.

**Comment by Suvadip-sana** [comment]
@Soujanya2004  And also I think there is need authentication/ logged in to give feedback about the platform. Because if there is no authentication or not allow after logged in, we did not track or prevent for spamming, which may cause database overflow issue. Because then unauthourized user can gave unlimited feedback.   So there is need authentication.     Still logged in I hide this feedback button. After that this button appear, for feedback input.

**Comment by Soujanya2004** [comment]
> @Soujanya2004 One clarification should visitor allow to delete their feedback? Or they only add the feedback. Rest functionality like delete operation and what to show, this permission only allow for admin? Because this approach follows in modern website.

feedback once given cannot be deleted by user, only admin will have access

**Comment by Soujanya2004** [comment]
> @Soujanya2004 And also I think there is need authentication/ logged in to give feedback about the platform. Because if there is no authentication or not allow after logged in, we did not track or prevent for spamming, which may cause database overflow issue. Because then unauthourized user can gave unlimited feedback. So there is need authentication. Still logged in I hide this feedback button. After that this button appear, for feedback input.

just like reviews user can give feedback only if they are logged in

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
I thought exactly that same thing . 
You assign me this.

**Comment by NK-Works** [comment]
@Soujanya2004 I can work on it if you want...
You can assign me...
Can make a PR by EOD

**Comment by Suvadip-sana** [comment]
@NK-Works  I am in

**Comment by Soujanya2004** [comment]
@NK-Works appreciate ur interest but @Suvadip-sana is already working on it 
@Suvadip-sana make sure u finish it by today?
