### ISSUE TITLE
[Feature Request]: Admin feature for Feedback.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement the delete feature for each and individual feature for Admin.  I built a new page in admin section where all the feedback display in card format. A delete button attached with each card for delete the review.

### Use Case

@Soujanya2004  Assign it to me. Assign it under `label-3` I want to built that feature in admin section.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Give it `label-3`

Because here the flow is -
- At first create a new page where display all feedbacks that present in database, in admin end (in card format). 
- Then With all of this associate a delete button.
- After that need to set up a new route for delete the feedback form database for admin.

**Comment by Soujanya2004** [comment]
ok got it
