### ISSUE TITLE
[Feature Request]: Admin control for display feedbacks in user page(user end)

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a checkbox for each  feedback  card in the admin section. If admin check this checkboxes of feedback card and click on save button.  Then only this feedback display for the user end.

This is require because no platform owner wants to show the negative feedback for their platform, if one user give negative feedback for your platform.

### Use Case

I add a `display: ` field for each feedback. Initially it set false when someone give the feedback.
When admin checked that box then it set to `true` and after clicking on `save` this reflect on the database. After that i display only that feedbacks which display property set to true, in front end.  For It's front end work I raised different ISSUE.

Hope my approach sounds good!

### Add ScreenShots

@Soujanya2004  Assign it  to me under `label-3`. I want to add this awesome feature.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004    I also think to implement the same for listing review part. It's not good to show extreme negative review for lists It's impact bad for user.    After completing all previous ISSUE, I would love to implement this same feature if you allow.

Let me know what you think on that approach.

**Comment by NK-Works** [comment]
@Soujanya2004 I can work on it if you want
You can assign me

**Comment by Soujanya2004** [comment]
@Suvadip-sana
