### ISSUE TITLE
[Feature Request]: Add Icons of Signup, login ,logout and your profile..

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 Add Icons of Signup, login ,logout and your profile..

### Use Case

 Add Icons of Signup, login ,logout and your profile..

### Benefits

Icons enhance user experience..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
> @Meetpidev in 'your profile' default image is set which acts as a icon so u can lev that

im not talking about that profile icon

**Comment by Soujanya2004** [comment]
@Meetpidev in 'your profile' default image is set which acts as a icon
so u can lev that
