### ISSUE TITLE
[Feature Request]: PRELOADER 

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ADD PRELOADER.. 

### Use Case

FOR LOADING ANIMATION..

### Benefits

FOR BETTER APPLICATION..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev can you add animation related to travelling like a map, plane anything
goes well with the website

**Comment by Meetpidev** [comment]
@Soujanya2004 
### ITs hard but i can try to make it..

**Comment by Soujanya2004** [comment]
@Meetpidev just try it if not add any unique loader

**Comment by Meetpidev** [comment]
@Soujanya2004 Request to review PR..
