### ISSUE TITLE
[Feature Request]: FORGOT PASSWORD

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ADD FORGOT PASSWORD

### Use Case

WHAT IF WE FORGOT THE PASSSWORD THAT SET BEFORE ?

### Benefits

BY THIS FEATURE WE CAN KNOW OUR PASSWORD..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev how do u plan to retrieve password

**Comment by Meetpidev** [comment]
@Soujanya2004 Since we are converting password into hash formet then we can not decode it now... so what we can do is that fetch user by email and in that email we send reset link.. and that password again stored in that user password.. by converting into hash..

**Comment by Soujanya2004** [comment]
okk got it , you can work on it @Meetpidev

**Comment by Meetpidev** [comment]
@Soujanya2004 rEVIEW Pr
