### ISSUE TITLE
[Bug]: Sorting Listings according to their Category  

### ISSUE THREAD

**Issue by azhar47-sk** [Soujanya2004/wanderlust-2024#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The category icons are not functional. We need to add functionality to those icons.

### Expected behavior

The listings should be shown in there categorized icon after clicking on it. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/88316d25-6ad6-4341-a8ee-beec48731a92)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by NK-Works** [comment]
@Soujanya2004 i can work on it if you want

**Comment by Soujanya2004** [comment]
its completed actually
thanks
