### ISSUE TITLE
[Feature Request]: Missing "Back" or "Previous Page" Navigation Button

### ISSUE THREAD

**Issue by shar2710** [Soujanya2004/wanderlust-2024#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, there's no apparent way to navigate back to the previous page. This can be frustrating for users who accidentally navigate away from a page or want to review previous information.

### Use Case

A visible "Back" or "Previous Page" button or link should be present on relevant pages, allowing users to easily return to the previous screen.
@Soujanya2004 please assign me

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@shar2710 where do u plan to implement this
