### ISSUE TITLE
[Feature Request]: Set the limit for list description input in backend.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As you can seen in the video. The description field has no limit. User can put description as input as they want. Which is not a good practice at all. Need to set limit for this.

### Use Case

I set the limit of 1000 letter for max input in description field. I think this is sufficient to describe any type of property.
If this limit exceed then it flash a error msg from backend.

### Add ScreenShots

https://github.com/user-attachments/assets/f45882d1-2f33-4f7b-b9ab-1137bc797ac1

@Soujanya2004  Please assign it  to me. I want to implement it.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana since its description it can be elaborated (with maybe  300words) , can u try to add show more option
