### ISSUE TITLE
Adding forgot password in login page

### ISSUE THREAD

**Issue by G-Rajashekar** [Soujanya2004/wanderlust-2024#40]
Adding forgot password will help the user to create  a new password

**Comment by G-Rajashekar** [comment]
can you assign this issue to me with labels gssoc-ext and  hacktoberfest

**Comment by Sourabh782** [comment]
hello @Soujanya2004 i see this issue been unresolved for about a month, can i work on this issue? 

![image](https://github.com/user-attachments/assets/fece1b5e-4ab4-42ab-b965-b8d56bcf9571)

**Comment by Soujanya2004** [comment]
@Sourabh782 can u implement regain password through email, where users receive their old password through mail for now
later we can implement rese password feature so

**Comment by Sourabh782** [comment]
> @Sourabh782 can u implement regain password through email, where users receive their old password through mail for now later we can implement reset password feature?
yes i can implement it

**Comment by Soujanya2004** [comment]
@Sourabh782 because we are not verifying their emails
i can give example@gmail.com and still signup

**Comment by Sourabh782** [comment]
> @Sourabh782 because we are not verifying their emails i can give [example@gmail.com](mailto:example@gmail.com) and still signup

Ohhkk understood, ok I'll implement sending old password

**Comment by Soujanya2004** [comment]
@Sourabh782 yeh please

**Comment by Sourabh782** [comment]
hii @Soujanya2004 can you help me with a thing?

**Comment by Sourabh782** [comment]
![image](https://github.com/user-attachments/assets/36dc8957-f007-4954-8d4c-f56aa8a23990)

I am getting this error when i start the app, can you look into it? :' ))

**Comment by Soujanya2004** [comment]
what have u added for atlas token in.env

**Comment by Sourabh782** [comment]
> what have u added for atlas token in.env

Mongouri

**Comment by Soujanya2004** [comment]
paste it here

**Comment by Sourabh782** [comment]
mongodb+srv://sourabhsinghrawat782:PzR2Sxd0SVViImI7@cluster0.jsmht.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

**Comment by Soujanya2004** [comment]
mongodb://127.0.0.1:27017/wanderlust 
try this

**Comment by Sourabh782** [comment]
> mongodb://127.0.0.1:27017/wanderlust

still gives same error

**Comment by Soujanya2004** [comment]
@Sourabh782 the issue is solved already sorry  i forgot to inform 
thanks for the interest
