### ISSUE TITLE
[Bug]: add reviews to every listing

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

currently one user can add only only review in the entire website, which is improper
user not able to add reviews to other listing after reviewing any one of the listing

### Expected behavior

user can add only one review to each listing

### Add ScreenShots

![Screenshot (260)](https://github.com/user-attachments/assets/a7cf06f7-89bb-4315-90d9-6052f7b80a76)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004   

If deployment is finish then there is many ISSUE like
- dark mode toggle is not working.
- Individual show route loading for long time.

If it's deployment issue. Otherwise I raised ISSUE?

**Comment by Soujanya2004** [comment]
@Suvadip-sana i guess its deployment issue, i will look into it

**Comment by Soujanya2004** [comment]
@Suvadip-sana can u please try to look into that issue, i am not able to revert the last commit also
i will label level 3 and assign u dont worry

**Comment by Suvadip-sana** [comment]
@Soujanya2004 Let me check

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Yes it's an ISSUE. I create a ISSUE for thuis.

**Comment by Soujanya2004** [comment]
@Suvadip-sana

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
I think there is no problem related to this ISSUE.  Here I verify it in your current deployment .
Please elaborate if still there have a problem. 

https://github.com/user-attachments/assets/f1b5b90f-afbd-4307-92b8-86a9ed1c7db2

**Comment by Soujanya2004** [comment]
@Suvadip-sana after deleting the review i am not getting option to add review again

**Comment by Suvadip-sana** [comment]
https://github.com/user-attachments/assets/ef7b049d-d69e-4224-9e92-6232c0c45ff5



See I just verify it in your current deployment. I got no error or trouble as you said. Please verify once more then inform me.

**Comment by Soujanya2004** [comment]
![Screenshot (274)](https://github.com/user-attachments/assets/eaf06105-b081-4a37-876e-356020f9edfe)
![Screenshot (275)](https://github.com/user-attachments/assets/c73a5d5f-20e6-4eae-89f4-8f6990c32d2a)
as u can see i have added no review still not having option to add new review

**Comment by Suvadip-sana** [comment]
In which card? Give me that cards screen short.  Are you try on your hosted server or local server?

**Comment by Soujanya2004** [comment]
![image](https://github.com/user-attachments/assets/54f8afea-ff1d-419d-9ca4-f4a15ab77dcc)
hosted server

**Comment by Soujanya2004** [comment]
@Suvadip-sana 
i am owner of that listing and unable to add review again

**Comment by Suvadip-sana** [comment]
> @Suvadip-sana i am owner of that listing and unable to add review again for others listing its working

Yes that's the logic added in backend from many time ego.
Basically The logic is that, listing owner is not allow to add reviews for there own list. Because that's not the way to show genuine and pure review for visitor.  Yes that logic is added in backend.


If you tell me to remove that logic means owner should allow to add the review for there own list. Then tell me.

**Comment by Soujanya2004** [comment]
@Suvadip-sana see i am able to add it for the first time but not after deleting it

**Comment by Meetpidev** [comment]
@Soujanya2004 whats the issue in this ??

**Comment by Soujanya2004** [comment]
no issues for now
