### ISSUE TITLE
[Bug]: Add dark mode for loader

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

loader is currently displayed on white bg

### Expected behavior

user who have choosen dark mode should be able to view loader in dark mode 
add black bg for loader

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
Yaaa. Assign it to me.
