### ISSUE TITLE
[Bug]: add hover effects to landing page

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

landing page doesnt have hover effects to cards making it little boring 

### Expected behavior

add creative and unique hover effects and animated image or gif or **video for banner image** in landing page

### Add ScreenShots

![Screenshot (266)](https://github.com/user-attachments/assets/416d8bc5-059a-4ef8-9189-57cadaf6dfc7)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@dev129

**Comment by Suvadip-sana** [comment]
@Soujanya2004 Assign it to me.

**Comment by dev129** [comment]
@Suvadip-sana, wait for sometime, i am solving it , since its my branch, if I need your help I will surely ask for it.

**Comment by Suvadip-sana** [comment]
> @Suvadip-sana, wait for sometime, i am solving it , since its my branch, if I need your help I will surely ask for it.

Thanks for inform me.

**Comment by Soujanya2004** [comment]
@Suvadip-sana since i had talked about this to @dev129 i will be assigning it to him

**Comment by Suvadip-sana** [comment]
@Soujanya2004 Yaaa
Sure!

**Comment by dev129** [comment]
@Suvadip-sana , I have an offer for you, since you are in top 23 already , if you could help me out , it would be nice for me too, since I am a beginner and a person like you could help me alot , what say ?

**Comment by Suvadip-sana** [comment]
@dev129 
Sure. Why not. You tell me your problem. If it possible to help you and have enough time for me. Then definitely. But it's not an offer though😂

**Comment by Soujanya2004** [comment]
> @Suvadip-sana , I have an offer for you, since you are in top 23 already , if you could help me out , it would be nice for me too, since I am a beginner and a person like you could help me alot , what say ?

🤣 u plan on giving money? @dev129
