### ISSUE TITLE
Google Authentication using Firebase 

### ISSUE THREAD

**Issue by samriddhitiwary** [Soujanya2004/wanderlust-2024#41]
I would like to implement Google authentication using Firebase. This feature would allow users to log in quickly and securely using their Google accounts, streamlining the authentication process and improving user experience. It can also enhance security by relying on Google’s authentication infrastructure, which is well-established and trusted.

![image](https://github.com/user-attachments/assets/85b4e507-7b35-4050-bab2-aca909ad6894)

**Comment by samriddhitiwary** [comment]
@Soujanya2004 Could you please assign this issue to me under gssoc-ext and hacktoberfest

**Comment by samriddhitiwary** [comment]
@Soujanya2004 ??

**Comment by geetanjalidubey9** [comment]
pla assign this to  me

**Comment by Soujanya2004** [comment]
@geetanjalidubey9 it's already assigned, you can raise a new issue and work on it

**Comment by geetanjalidubey9** [comment]
Ok
