### ISSUE TITLE
Edit .readme file

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#42]
add steps required to set the repo in localhost

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
And please add gssoc-ext label

**Comment by Soujanya2004** [comment]
> I want to work on it. Can you please assign it to me? And please add gssoc-ext label

Here you go

**Comment by AnujSaha0111** [comment]
> Here you go

Solved it in #44
