### ISSUE TITLE
[Feature Request]: SET LIMIT IN UPLOADING IMAGES WHILE CREATE NEW LISTING AND EDIT LISTING

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

SET LIMIT IN UPLOADING IMAGES WHILE CREATE NEW LISTING AND EDIT LISTING.. WE ARE UPLOADING ANY NUMBER OF PICTURES.. THERE SHOULD BE LIMITATAION ON IT..

### Use Case

MINIMUM NUMBERS OF PICTURES AREALLOWED TO UPLOAD.. SO IN DB.. THERE IS NO STORED MULTIPLE IMAGE FOR ONE LISTINGS..

### Benefits

 IN DB THERE IS NO STORED MULTIPLE IMAGE FOR ONE LISTINGS..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 Can i work on this ?

**Comment by Suvadip-sana** [comment]
#391  #392
