### ISSUE TITLE
[Feature Request]: Add Chatbot Feature

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add Chatbot Feature to Enhance User Experience

### Use Case

chatbot

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
#422
