### ISSUE TITLE
[Feature Request]: I want to create different controller for different types of route.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

For now your `app.js` file have too much congested, because of admin, user, legal and profile route. 
For this behaviour other development was stucked in, If someone already make changes on this file and that PR is not marge yet,

his create too much problem. 

### Use Case

I create 3 different controller for `admin`, `user` & `profile` controller like you have `listing` & `review` controller.

For this changes, your `app.js` file main server looks nit & clean. Also developer have enough space to do their work in different feature. That helps lot.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1341d36b-a429-4a37-8cfd-0d11be6b55dd)
![image](https://github.com/user-attachments/assets/a88a96fa-f832-45bc-9376-35313e4c5064)
![image](https://github.com/user-attachments/assets/4775b7bf-55c9-4f57-9927-ef6024baef57)
![image](https://github.com/user-attachments/assets/f6de5837-2c78-4936-9605-b4eaa336db4a)
![image](https://github.com/user-attachments/assets/ccc7d3dd-9369-4e20-afaf-6ff61e3bc688)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana u have 14 opened issues
please be quick as others are asking me to assign them
