### ISSUE TITLE
[Feature Request]: Listing Section Design

### ISSUE THREAD

**Issue by dev129** [Soujanya2004/wanderlust-2024#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi @Soujanya2004 

### Issue: Listing Section Design Improvements

**Description:**
The current design of the listing section could be optimized for better usability, aesthetics, and consistency with the rest of the application. This improvement aims to enhance the visual appeal and user experience of the section.

**Problems Identified:**
1. **Inconsistent Spacing:** The spacing between list items is inconsistent, making the section look cluttered and hard to read.
2. **Typography Issues:** The font size and weight could be adjusted for better readability and hierarchy. Currently, all text appears too similar, reducing the visual flow.
3. **Alignment Problems:** Some elements within list items are not aligned correctly, creating a disorganized appearance.
4. **Lack of Visual Feedback:** There's minimal interactive feedback (such as hover effects) on list items, which reduces the interactive experience.
5. **Color Scheme and Contrast:** The color scheme could be improved to ensure better contrast and accessibility, particularly for text and background colors.

**Proposed Enhancements:**
- **Consistent Spacing**: Apply uniform padding and margins to create a balanced layout across the list items.
- **Typography Adjustments**: Adjust font size, weight, and color to establish a clearer visual hierarchy (e.g., larger, bolder headings for list item titles).
- **Alignment**: Ensure all elements in each list item are properly aligned for a clean, organized look.
- **Interactive Feedback**: Add hover effects to list items to indicate interactivity and improve user experience.
- **Color and Contrast**: Refine the color scheme to enhance readability and accessibility, following WCAG contrast guidelines.

**Additional Notes:**
Please reference the design guidelines or existing styles within the project for consistency. A prototype or mockup demonstrating the intended design changes would be helpful.

### Use Case: Improved Listing Section Design

The listing section is a crucial part of user interfaces that displays information or content in a structured way. By refining the design, this section can serve a wide range of use cases, such as displaying items in a catalog, showing a list of articles, or presenting user profiles in a social feed.

**Key Use Cases Include:**
1. **Product Listings**: In an e-commerce site, clear and attractive product listings help users quickly scan and choose items.
2. **Content Feeds**: Blogs, news sites, or social platforms use listing sections to display articles or posts, making it easy for users to find content of interest.
3. **User Directories**: Applications like social networks or employee management platforms benefit from well-designed listings that let users browse profiles effortlessly.
4. **Task Management**: In productivity apps, a well-organized listing design helps users keep track of tasks, deadlines, and priorities.

### Benefits of a Refined Listing Section Design

Improving the listing section’s design provides both user experience and business benefits:

1. **Enhanced Usability**: Clearer spacing, consistent alignment, and visual hierarchy make information easier to scan and understand, improving user engagement.
  
2. **Increased Accessibility**: By following color contrast guidelines and improving text readability, the design becomes more accessible to users with visual impairments, broadening the audience.

3. **Stronger User Engagement**: Adding hover effects and other visual cues can make the interface feel more interactive, keeping users engaged as they browse through content.

4. **Higher Conversion Rates**: In scenarios like e-commerce or subscription-based sites, well-designed listings make products or options more appealing, which can lead to higher click-through and conversion rates.

5. **Consistent Brand Perception**: A well-designed listing section reflects professionalism and attention to detail, reinforcing a consistent and appealing brand image.

By focusing on these improvements, the listing section will better meet user needs, contribute to overall product usability, and support business objectives.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dev129** [comment]
Hi @Soujanya2004 , please check this 

Dark mode:
![image](https://github.com/user-attachments/assets/a0d99ea8-3ab7-4c51-b1fc-ce6df058eb26)

Light Mode:
![image](https://github.com/user-attachments/assets/c85d8b4a-67b4-4bdc-a1da-8bf85763a488)

**Comment by dev129** [comment]
This is the mobile view :
![image](https://github.com/user-attachments/assets/c8c12735-2003-4b8d-8970-6ed2de6caa43)

**Comment by Soujanya2004** [comment]
@dev129 in dark mode it's supposed to be dark, here cards are displayed with white bg
other contributor has already raised pr so i will close this

**Comment by dev129** [comment]
Wait a minute @Soujanya2004 , you could have tell me about that, i mean if you wanted edits atleast I must vetold about that , you dont ha e the right to change kike that

**Comment by Soujanya2004** [comment]
@dev129 see its all about who does job faster 
one of the contributor had finished the job already , what will be the use if i merge another pr which does the same task

**Comment by Soujanya2004** [comment]
@dev129 its up to the project admin to choose the feature that has to be added to their website

**Comment by dev129** [comment]
Thanks alot @Soujanya2004 here is a much more improvised view 

Light View:
![image](https://github.com/user-attachments/assets/381f0086-dff5-4793-8d06-4911bc18271d)

Dark View:
![image](https://github.com/user-attachments/assets/5a057bd0-7284-4cea-a698-aaea50803c80)

**Comment by Soujanya2004** [comment]
@dev129 please pull code before raising pr because there is like feature added and many other improvements

**Comment by Soujanya2004** [comment]
rest all is ok for me

**Comment by dev129** [comment]
I have updated it and the only chang i see is in the landing page 
![image](https://github.com/user-attachments/assets/f08b9551-5ca4-4a25-b31d-2fdce05c9f83)
rest i have not much changes , but a serious concern is that your gitignore file is not working

**Comment by Soujanya2004** [comment]
@dev129 about the gitignore i cant do anything ryt?

**Comment by Soujanya2004** [comment]
> I have updated it and the only chang i see is in the landing page ![image](https://private-user-images.githubusercontent.com/76431221/384586160-f08b9551-5ca4-4a25-b31d-2fdce05c9f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzc3MTUsIm5iZiI6MTczMTEzNzQxNSwicGF0aCI6Ii83NjQzMTIyMS8zODQ1ODYxNjAtZjA4Yjk1NTEtNWNhNC00YTI1LWIzMWQtMmZkY2UwNWM5ZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzVmYmE1MjcyYTU5OWE1YzdiYmMwZGVkNjc0NGVlMjIyYzZiYzkwYWY0MGQwNjhlM2NjOGI1MzRlYWVmYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fm0Kx05MrGiae67t2vzgt0XoX1IiTDTXCEs1sKjSI5w) rest i have not much changes , but a serious concern is that your gitignore file is not working

![image](https://github.com/user-attachments/assets/0c0b82d6-d558-4e3f-ae0b-6c558115978f)

**Comment by dev129** [comment]
And that is what I am thinking , why ? and what will we do if someone directly perform commit operation ?

**Comment by Soujanya2004** [comment]
@dev129 not many are facing that issue actually

**Comment by dev129** [comment]
Yeah but problems don't inform when coming.

**Comment by Soujanya2004** [comment]
did u check the updated listing??

**Comment by dev129** [comment]
in the app.js file because that i updated by me already.

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/58ffa6b4-1b4c-4651-9afb-899bd0c0c933)

**Comment by Soujanya2004** [comment]
fine then raise pr
