### ISSUE TITLE
[Feature Request]: UPDATE PASSWORD

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

WE CAN ALSO UPDATE OUR PASSWORD..  THERE IS DIFFERENCE BETWEEN RESET , UPDATE PASSWORD.. THATS WHY WE NEED THIS FEATURE ALSO.. 

### Use Case

user can update his password..

### Benefits

secured password, user can update their password..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 can i work on it ?

**Comment by Soujanya2004** [comment]
@Meetpidev where are u seeing update password feature

**Comment by Meetpidev** [comment]
@Soujanya2004 in many apps there is the feature of updating password.. like facebook,twitter,banking apps.. amazon etc...
