### ISSUE TITLE
[Feature Request]: DUMMY PAYMENT INTEGRATION

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

THERE SHOULD BE PAYMENT OPTION SO THAT WE CAN BOOKED LISTING OR BUY LISTING..

### Use Case

TO BOOK/PURCHASE LISTING..

### Benefits

WE CAN DO ONLINE PAYMENT

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
when one listing is booked/purchased then we can display booked mark on that listing..

**Comment by Meetpidev** [comment]
@Soujanya2004 Can i work on it ?

**Comment by Soujanya2004** [comment]
@Meetpidev the thing is booking functionality is not implemented
user can just login see and add listing, reviews thats it

**Comment by Meetpidev** [comment]
@Soujanya2004 Why booking is not happend ? we should add it.. for the meaning of present listing.. otherwise there is no meaning to add,review listing

**Comment by Meetpidev** [comment]
@Soujanya2004 think about real senario.. if im property owner and i see your website and know that there is no booking system then why i add my listing details in it ?

**Comment by Soujanya2004** [comment]
@Meetpidev  i know that ryt
 i have already the issue u can work on it

**Comment by Meetpidev** [comment]
@Soujanya2004 so i can start to make it right ?

**Comment by Soujanya2004** [comment]
@Meetpidev actually somebody just took that issue 
u can work on payment feature ryt after they finish
they may finish it by tomorrow is it fine?

**Comment by Meetpidev** [comment]
@Soujanya2004 okay but after that what can i improve in that ? if hes already finished issue

**Comment by Meetpidev** [comment]
@Soujanya2004 and if he is not able to finish this feature then requestsed to assign me...

**Comment by Soujanya2004** [comment]
@Meetpidev for sure i will

**Comment by Soujanya2004** [comment]
> @Soujanya2004 okay but after that what can i improve in that ? if hes already finished issue

i will assign u this dont worry
