### ISSUE TITLE
[Feature Request]: ADDING CONTACTUS FORM

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

THERE SHOULD BE CONTACTUS FORM BY WHICH USER CAN CONTACT

### Use Case

 USER CAN CONTACT

### Benefits

 USER CAN CONTACT VIA EMAIL/PHONE_NUMBER

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 Can i work on it ?

**Comment by Soujanya2004** [comment]
@Meetpidev there is already in the footer

**Comment by Meetpidev** [comment]
@Soujanya2004 there should be saperate form for contacUS for user experience.. because if someone wants to only contact then they can slect option from navbar.. they dont need to go to the footer

**Comment by Meetpidev** [comment]
@Soujanya2004 just think that if there is 10000 listing and for only contact user have to gothrough these many listings..

**Comment by Soujanya2004** [comment]
@Meetpidev and navbar is already crowded with lots of link

**Comment by Soujanya2004** [comment]
@Meetpidev contact us form is already available in navbar

**Comment by Meetpidev** [comment]
@Soujanya2004 okay got it
