### ISSUE TITLE
[Bug]: Authentication error

### ISSUE THREAD

**Issue by harshbhar0629** [Soujanya2004/wanderlust-2024#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When user try to login then it can directly login either it have account or not.

### Expected behavior

When user try to login then first it must have account on platform.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana can u check that

**Comment by Meetpidev** [comment]
@Soujanya2004 Its working perfectly fine.. system throws an error if user/password not avilabale

**Comment by Soujanya2004** [comment]
@Meetpidev yeh i am explaining him that
