### ISSUE TITLE
[Documentation Update]: MAKE UPDATE AND RESET PASSWORD PAGE  STYLED

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

MAKE IT STYLED
![image](https://github.com/user-attachments/assets/61d5a318-b010-4cb0-83dc-309a864f26b8)

### Suggested Change

IT SHOULD BE STYLED

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanskritim2302** [comment]
Hi! I’m also interested in helping to enhance the project’s documentation style. If there’s any part of the documentation you’d like support with, feel free to reach out. I’d be happy to assist! @Soujanya2004

**Comment by sanskritim2302** [comment]
@Meetpidev I’m not a maintainer, just a contributor. I’m eager to contribute to the project, and if there’s anything I can help with, feel free to let me know! @Soujanya2004

**Comment by Soujanya2004** [comment]
@sanskritim2302 it works on first come basis so i am assigning to Meetpidev
