### ISSUE TITLE
[Feature Request]: Limit to set the tag for list.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As you can see in the attached screenshot. If there is many tag associate with one tag it's cause of destructure the card design in user end. It's styling was broken. 

And I think there should be no more than 4 tag was needed for one list.

### Use Case

- So I modify the tags display for each card. I display the tags Icon same to same as present in the filter options along with this website red color. Which looks more beauitifull and doesn't affect it's style.
- Also I set the backend logic to limit this tag association of maximum 5 tag for one list in every possible input section like in -- `new list create form`, `edit list form`, also in `admin dashboard`

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3ef0ed3b-3f15-4b1a-a355-d215a501f9a9)

@Soujanya2004   Assign it to me under `label-3` because there is front end work needed along with backend logic in three different  position 1. `new list create form`  2. `edit list form`  3. also in `admin dashboard`

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana make it limited to 3

**Comment by Suvadip-sana** [comment]
> @Suvadip-sana make it limited to 3

Okkk
