### ISSUE TITLE
[Feature Request]: ABOUTUS PAGE

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

THERE IS MISSING ABOUTUS PAGE..

### Use Case

IT SHOULD BE THERE TO KNOW ABOUT WEBISTE MORE.. IN THAT WE CAN INCLUDE NOT ONLY ABOUT WEBSITE BUT ALSO INCLUDE WORKFLOW.. SO THAT USER CAN GET BETTER IDEA..

### Benefits

USER CAN GET BETTER IDEA..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 hey.. look in your repo.. you have already about.ejs.. when i am starting to work on this.. i see that there is already about.ejs page....

**Comment by Meetpidev** [comment]
@Soujanya2004 but you dont include that in navbar.. and also you dont defined the rout that render about.ejs

**Comment by Soujanya2004** [comment]
@Meetpidev fine then just add it in navbar 
maybe someone altered it

**Comment by Meetpidev** [comment]
@Soujanya2004 as of now its looks like normal.. not styled description.. 
![image](https://github.com/user-attachments/assets/406eca24-e427-44bb-9399-a97c8a1ad8da)

can i make change in styling in that paragraphs & contact details ?? and can i include dummy review/possitive feedbakcs in it ??

**Comment by Soujanya2004** [comment]
@Meetpidev please change the entire content also
because its irrelevant and sure add ur own styles and images 
use readme file if u want more specifications

**Comment by Soujanya2004** [comment]
@Meetpidev there is link to access this about us page in footer

**Comment by Suvadip-sana** [comment]
> @Meetpidev there is link to access this about us page in footer do u think we need that in navbar or footer?

@Soujanya2004 
Exactly. This type of about us, terms & condition, Privacy Policy type legal pages for website always present in Footer only. Means that's an standard and good practice. 

If About us page is in navbar then privacy policy, terms and condition page also be there? 😂😂🤣

That changes is not good practice in my #opinion. If play with style of that page then fine👍

**Comment by Meetpidev** [comment]
@Soujanya2004 so should i include about Us [page in navbar or not ??

**Comment by Meetpidev** [comment]
@Soujanya2004 it should be there in navbar as well as footer.. because the generally most of the website include it in navbar

**Comment by Meetpidev** [comment]
@Soujanya2004 Im done with about Us page styleing after so much time to spend .. Sent PR.. please check..

**Comment by Soujanya2004** [comment]
@Meetpidev raise issue and add in navbar
because knowing wt this website is about is very important
