### ISSUE TITLE
[Bug]: List card color pallet

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/df1c978f-a272-445f-bdad-5a9c5c6ab3e9)

Is this font color of card is justify our website color pallet. I don't think. It's need to be change.

### Expected behavior

@Soujanya2004  Assign it to me. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Suvadip-sana yes please change to same red used in website

**Comment by Suvadip-sana** [comment]
@Soujanya2004  I told about the card heading and price section, Which is black and gray previously. Now it's blue. 

Here black and gray is good fit i think

**Comment by Soujanya2004** [comment]
@Suvadip-sana i was talking about the price make it red na
let button be same

**Comment by Soujanya2004** [comment]
@Suvadip-sana there are issues which is opened from last week please look into that

**Comment by Suvadip-sana** [comment]
@Soujanya2004    Yes yes. Don't worry. I submit all of this.  I already start working on this
