### ISSUE TITLE
[Bug]: change text color for dark theme

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot (271)](https://github.com/user-attachments/assets/a3c09585-0504-45fc-860c-1ccb7cbd8498)
change text color 

### Expected behavior

change text color which is blue to red(same used everywhere in website)
and increase the price font size a little

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 Ofcourse.. ready to work on it...

**Comment by Soujanya2004** [comment]
@Meetpidev just add msg there so that i can assign u
