### ISSUE TITLE
[Feature Request]:  styling the update password page

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 styling the update password page

### Use Case

 styling the update password page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev #458 is same ryt?

**Comment by Meetpidev** [comment]
YUP.. I will reset the title..

**Comment by Meetpidev** [comment]
> YUP.. I will reset the title..

DONE..

**Comment by Soujanya2004** [comment]
@Meetpidev so i will close this
