### ISSUE TITLE
[Bug]: Add Popup Sign-in Form for Non-Logged-In Users with Time Interval Trigger

### ISSUE THREAD

**Issue by dipexplorer** [Soujanya2004/wanderlust-2024#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, the site does not prompt non-logged-in users to sign up, which could lead to missed opportunities for user registration. To improve user engagement, we need to implement a timed popup that displays a sign-up form if the user is not logged in. This popup should appear after a certain time interval (e.g., 30 seconds) and prompt the user to sign up or log in.

### Expected behavior

- A popup window with a sign-up form appears for non-logged-in users after a specified time interval.
- The popup window should have a close button, allowing users to dismiss it if they are not interested in signing up.
- Ensure that this popup does not repeatedly display during the same session once dismissed.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@dipexplorer i would suggest u to add a nice bg related to travelling with a message 'welcome to wanderlust' and display signup button on pop up card

**Comment by dipexplorer** [comment]
@Soujanya2004 ,

If you have any background image in mind, you can share it.

**Comment by Soujanya2004** [comment]
@dipexplorer 
![image](https://github.com/user-attachments/assets/a7f3c4aa-f7a8-45f6-8cb2-b2373c6322a7)
