### ISSUE TITLE
[Feature Request]: LISTING LIKE FEATURE 

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

THERE SHOULD BE FEATURE TO LIKE LISTING

### Use Case

BENIFITS TO FIND BEST LISTINGS

### Benefits

BENIFITS TO FIND BEST LISTINGS

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev follow same instruction mentioned in #335

**Comment by Soujanya2004** [comment]
@Meetpidev make sure its before tomorrow evening
