### ISSUE TITLE
[Feature Request]: add banner video/image for homepage

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add a landing banner related to travel in homepage just below filter icons
(also make filter icons smaller)

### Use Case

![image](https://github.com/user-attachments/assets/9694ff04-698c-4eec-9f80-27eef5e62310)
reference website

### Benefits

improve ui

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev i think this will look good if we implement it properly
we can add load more options after 4 rows of listing to view more listings

**Comment by Soujanya2004** [comment]
@Meetpidev we can remove the container for the filter icons and reduce size then add the banner 
just like the image with proper style

**Comment by Meetpidev** [comment]
> @Meetpidev i think this will look good if we implement it properly we can add load more options after 4 rows of listing to view more listings

if we give more option to load and see more option then what if there is more than 100 listing ? user can click more btn ? to see all the listing.. ? its not good user experince..

**Comment by Soujanya2004** [comment]
@Meetpidev just take Instagram as example it adds loader for loading more content ryt?

**Comment by Soujanya2004** [comment]
@Meetpidev

**Comment by Meetpidev** [comment]
@Soujanya2004 I tried but its not lokking good..

**Comment by Soujanya2004** [comment]
fine

**Comment by Meetpidev** [comment]
@Soujanya2004 Please provide me image / video  you want to put in back ground

**Comment by Meetpidev** [comment]
@Soujanya2004 i can try again if you provide me what you want to put in background
