### ISSUE TITLE
[Feature Request]: UI enhancement in index page card.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Now in index page all the cards are clickable itself so I don't think there is need any `Show in details` type button associated with all  list card.

### Use Case

I want to remove that `Show in details` button for all card. It enhance the card UI because in this ISSUE #461 Where I structure the tags for individual list.  It help to implement that. And also this `Show in details` button is not make any sense now.

### Add ScreenShots

![Uploading image.png…]()

@Soujanya2004  Assign it to me

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 Please add image.. where do you want to improve

**Comment by Soujanya2004** [comment]
its just removing a button and changing the color ryt
