### ISSUE TITLE
[Feature Request]: add signup option when user isnt logged in

### ISSUE THREAD

**Issue by Riyachauhan11** [Soujanya2004/wanderlust-2024#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Ill be adding sign up option here instead of go back as it makes more sense to be placed here for first time users,
![image](https://github.com/user-attachments/assets/a558c897-87c5-40bb-a7b8-fc44b259f133)

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Riyachauhan11 already other contributor is working with this issue
