### ISSUE TITLE
[Bug]: change shade of red used

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there are different shades of red used in the website 

### Expected behavior

i want uniform color to be used everywhere 
so change every element using red to **#ff385c** shade (including navbar links, icons, scroll up icons, buttons of every page etc..)
on hovering use **#FF5A5F** shade everywhere a hover effect is given

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
@Soujanya2004 
assign it
