### ISSUE TITLE
[Bug]: improve contact us page ui

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the container currently is vertical and unappealing
user has to scroll down to see entire form 

### Expected behavior

make the form vertical, add images or gifs to improve user experience

### Add ScreenShots

![Screenshot (273)](https://github.com/user-attachments/assets/a6054755-23f5-4b9c-ae4f-ea2d66db349c)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
@Soujanya2004 
assign it
