### ISSUE TITLE
[Feature Request]: add travel stories page (blog)

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

user who are signed up should be able to add their experiences along with their travel photos (places they traveled, culture of a place, people there, food, cost etc.)
other users should be able to like the blog that is posted here
navbar should have the access link to this page
Users can document their travels with photos, videos, and text entries

### Use Case

to enhance user activity on the website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
@Soujanya2004 
assign this

**Comment by Soujanya2004** [comment]
@dipexplorer why is the file fetch_head

**Comment by dipexplorer** [comment]
@Soujanya2004 ,
which file could u explained

**Comment by Soujanya2004** [comment]
u hv pushed the file in main folder

**Comment by Meetpidev** [comment]
@Soujanya2004 it seems that he not active this time so can i send PR of it ??

**Comment by Soujanya2004** [comment]
@dipexplorer progress only 2 hrs left

**Comment by dipexplorer** [comment]
raise the PR within an hour

**Comment by Meetpidev** [comment]
@Soujanya2004 please close the issue that is solved.. so in this 30 min.. if possible then we can send PR about it

**Comment by Meetpidev** [comment]
@Soujanya2004 there are many issue is still open even if its solved..

**Comment by Meetpidev** [comment]
@Soujanya2004 At one thing you made mistake.... many people raise issue in large number as you can see present.. at the end they can not complete.. yeah, after the gssoc they completed but as a gssoc participate they can not finished.....

it would be better if you restricted to raise the issue by someone so that everyone can get chnage to solve it under gssoc.. : 
**just a suggestion...**

**Comment by Meetpidev** [comment]
@Soujanya2004 

I'm thrilled to be part of contribute to this amazing project. The experience has been incredibly enriching, and I appreciate the support from the maintainers. I'm committed to continuing my contributions even after GSoC, as I believe in the project's mission and want to help it grow further. I look forward to collaborating with everyone and contributing to our shared goals in the future!
