### ISSUE TITLE
[Bug]: CHANGE STYLING OF BTNS..

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

BOOK BTN IS NOT DISPLAYING

### Expected behavior

SHOULD BE DISPLAY TO BOOK

### Add ScreenShots
![image](https://github.com/user-attachments/assets/cfb9753c-f70a-4204-8321-21e20a7d6873)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev i will label after reviewing pr

**Comment by Meetpidev** [comment]
@Soujanya2004 did you check ?

**Comment by Soujanya2004** [comment]
![image](https://github.com/user-attachments/assets/967f9ee3-9be2-4a8b-bbdf-ad97a9735452)

**Comment by Soujanya2004** [comment]
@Meetpidev please change the style for all buttons displayed in this page

**Comment by Soujanya2004** [comment]
@Meetpidev u can work on payment feature

**Comment by Meetpidev** [comment]
@Soujanya2004 
i can not see the bok btn. in listing.. is it really display ?

**Comment by Soujanya2004** [comment]
@Meetpidev check hosted server

**Comment by Meetpidev** [comment]
> @Meetpidev please change the style for all buttons displayed in this page

I RAISED ISSUR FOR IT ?

**Comment by Soujanya2004** [comment]
issue number?

**Comment by Meetpidev** [comment]
> issue number?

 no im asking that can i raised separate issue for it ?

**Comment by Soujanya2004** [comment]
@Meetpidev no work with this issue
change the title
