### ISSUE TITLE
[Bug]: Main server file changed. Not reflect the re structured file

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The different controller is there but the same route present in the `app.js` file

Which is not supposed to be. I think need o eliminate that duplicate route, Otherwise it create the unexpected error.

### Expected behavior

@Soujanya2004  Assign it to me. I think this happen because of before marging my restructuring the main server PR some one changes done in this file. So that override here.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Soujanya2004 

It's not supposed to be `label-1` work that justify it's solution of the problem. You can verify that. Please check once.

**Comment by Soujanya2004** [comment]
@Suvadip-sana i will review the pr and change the label no worries

**Comment by dipexplorer** [comment]
@Soujanya2004 
i fixed that in my pr

**Comment by Soujanya2004** [comment]
@Suvadip-sana then shall i close it?

**Comment by Suvadip-sana** [comment]
@Soujanya2004 Yes but still there is duplicate route.

![image](https://github.com/user-attachments/assets/f0e9313f-2e94-48a5-a85a-2a3ac9e3495b)
@dipexplorer  He removed this only
 But here is more duplicate route

![image](https://github.com/user-attachments/assets/124200dd-b1c9-4dbc-9d1c-2a5d6ebe5d5f)

Here

**Comment by Soujanya2004** [comment]
@Suvadip-sana fine then remove duplicates

**Comment by Suvadip-sana** [comment]
@Soujanya2004   Cool. I will made PR in just 10 min
