### ISSUE TITLE
[Feature Request]: ANIMATIONS ON LIKE BTN

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ANIMATIONS ON LIKE BTN

### Use Case

ANIMATIONS ON LIKE BTN

### Benefits

BETTER UI

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 can i add confetti animation ??

**Comment by Soujanya2004** [comment]
@Meetpidev just add pop up, like u see in Facebook or Instagram 
the heart icon pops up and likes

**Comment by Meetpidev** [comment]
> @Meetpidev just add pop up, like u see in Facebook or Instagram the heart icon pops up and likes

i made this animation but its not showing to user as we redirecto to that listing after we like.. and if we not redirect it then we have to send success msg.. and that is not good at all..

**Comment by Meetpidev** [comment]
@Soujanya2004  ??

**Comment by Soujanya2004** [comment]
> > @Meetpidev just add pop up, like u see in Facebook or Instagram the heart icon pops up and likes
> 
> @Soujanya2004 i made this animation but its not showing to user as we redirecto to that listing after we like see the code.. and if we not redirect it then we have to send success msg.. and that is not good at all..

try to do it or else lev it like before

**Comment by Meetpidev** [comment]
@Soujanya2004 its not happend.. tried it a lot..

**Comment by Meetpidev** [comment]
@Soujanya2004 so you can close this issue
