### ISSUE TITLE
[feature Enhacement] : dark mode toggle.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Soujanya2004/wanderlust-2024#5]
### **Is your feature request related to a problem? Please describe.**
there is not preferences in the website to toggle between dark and light mode.I will create a toggle in the navabar which will allow the user to toggle between dark mode and light mode.

**Comment by Soujanya2004** [comment]
@T-Rahul-prabhu-38 will you be able to create toggle functionality or just the button

**Comment by T-Rahul-prabhu-38** [comment]
toggle functionality

**Comment by T-Rahul-prabhu-38** [comment]
im soryr , im not able to fix it
