### ISSUE TITLE
[Feature Request]: SCROLLBAR STYLE

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 ADD SCROLLBAR STYLE(CUSTOM COLORS) AND IT SHOULD BE SMOOTH TO SCROLL

### Use Case

 SCROLLBAR STYLE

### Benefits

ATTRECTIVE

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4126a980-5a89-4cc3-b1f8-7c776bec5c61)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev can i see a reference

**Comment by Meetpidev** [comment]
@Soujanya2004 LIKE THIS..
![image](https://github.com/user-attachments/assets/43e578a5-33bd-4f1d-bfe0-5a540179861d)
CUSTOM SCROLLBAR.. WITH SUITABLE COLORS.. AND SMOOOTH TO SCROLL

**Comment by Soujanya2004** [comment]
fine add it with red color

**Comment by Meetpidev** [comment]
@Soujanya2004 Please Review PR..

**Comment by Soujanya2004** [comment]
#ff385c use this shade only

**Comment by Meetpidev** [comment]
https://github.com/user-attachments/assets/1807e339-b1e6-4208-913c-9cefe087be11

**Comment by Meetpidev** [comment]
@Soujanya2004 Review again
