### ISSUE TITLE
[Documentation Update]: update styling of btns

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

UPDATE SYLING OF BTNS
![image](https://github.com/user-attachments/assets/b3a40bff-7277-478e-b505-9ffda4a9f8fe)

### Suggested Change

UPDATE SYLING OF BTNS

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev why is this closed,

**Comment by Soujanya2004** [comment]
i wanted u to arrange the buttons horizontally

**Comment by Meetpidev** [comment]
> @Meetpidev why is this closed,

BY MISTAKE
