### ISSUE TITLE
how to contribute / setting up the project locally

### ISSUE THREAD

**Issue by kcjod** [Soujanya2004/wanderlust-2024#51]
How can I contribute to the repository and steps to setup the project locally

**Comment by Soujanya2004** [comment]
Document how to run the project locally, because it uses .env files tell them how to set up those @kcjod

**Comment by Soujanya2004** [comment]
@kcjod what happened, any progress

**Comment by kcjod** [comment]
Yeah, i have raised a PR. But it might causing you conflicts. So, I'm checking them

**Comment by ambrishgoswami** [comment]
Document how to run the project locally, because it uses .env files tell them how to set up those
