### ISSUE TITLE
[Bug]: HOMEPAGE NAVBAR STYLE 

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

FIX STYLING OF NAVBAR IN HOMEPAGE

### Expected behavior

FIX STYLING OF NAVBAR IN HOMEPAGE

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9ee2ad31-f50a-46c4-8a99-8eceb6e9c77a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
@Meetpidev    If this is assign to you you please add one more nav link for the route `/feedback`  for `Feedbacks`
Because I currently  working on it. If you add this while styling then it's good for adjust the style. Add it both desktop nav and mobile nav. That's good for me also.

**Comment by Meetpidev** [comment]
@Suvadip-sana okay.. but  there is opion of fedback in footer.. so i dont think that we need to include feedback in navbar.. navbar wil becomes too long..

**Comment by Meetpidev** [comment]
@Suvadip-sana did you ask to the maintainer about includeing feedback option in navbar ot not ??  if maintainer has no problem with it then i will include it...

**Comment by Suvadip-sana** [comment]
@Meetpidev See in footer feedback option is only for submit the feedback. After that for display it, Need a page. So I told you to just add that page link in nav. All other full functionality are built by me.  I also add this small changes on nav, But you are going to add the styling, That's why I tell you to add for implement better styling for all of this. 
Nothing else.   You just add a link of `/feedback` route link of heading `Feedback`  That's it.

**Comment by Soujanya2004** [comment]
@Meetpidev  let the feedback form be in footer no need to add in navbar

**Comment by Soujanya2004** [comment]
what changes u wanted to bring in navbar style its good now

**Comment by Suvadip-sana** [comment]
@Soujanya2004    No no I did not add to the form link in navbar. I want to add the feedback show page in navbar, Which is currently show page not found after feedback submission. Go it?

> @Meetpidev let the feedback form be in footer no need to add in navbar

**Comment by Meetpidev** [comment]
> what changes u wanted to bring in navbar style its good now

navbar style is not good.. see the provided image

**Comment by Soujanya2004** [comment]
@Suvadip-sana ok got it 
@Meetpidev add it, dont change style

**Comment by Meetpidev** [comment]
> @Suvadip-sana ok got it @Meetpidev add it, dont change style

should i add feedback option as well ??

**Comment by Soujanya2004** [comment]
no just link for the feedback page

**Comment by Meetpidev** [comment]
> no just link for the feedback page

link means what ? i dont understand what you are saying ? should i put feedback option like  other tags ? when we click on it we redirect to feedback page..

**Comment by Meetpidev** [comment]
> > no just link for the feedback page
> 
> @Soujanya2004  link means what ? i dont understand what you are saying ? should i put feedback option like other tags ? when we click on it we redirect to feedback page..
