### ISSUE TITLE
[Feature Request]: Displaying feedbacks in user end.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a new route for feedbacks `/feedbacks` with proper backend support to implies the extend the feature of the ISSUE #352  & #353 

Where I only display that feedbacks which `display` field set to `true` bye admin. With the proper line. 

### Use Case

@Soujanya2004  Assign it under `label-3` 

I display the each feedbacks in card format like review card along with name, comments and stars.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Suvadip-sana hey did you remove app.js file in previous pr ?

**Comment by Meetpidev** [comment]
@Suvadip-sana ??
