### ISSUE TITLE
[Bug]: APP.JS FILE MISSING IN MAIN BRANCH

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

APP.JS FILE MISSING IN MAIN BRANCH

### Expected behavior

should be there

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0686c4ab-1566-4ab4-af70-b46b70ab75f8)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@Soujanya2004 see you delete app.js file.. in previous PR..

**Comment by Meetpidev** [comment]
@Soujanya2004 solve this soon

**Comment by Soujanya2004** [comment]
@Suvadip-sana

**Comment by Meetpidev** [comment]
@Soujanya2004 can i add it? i will send PR

**Comment by Meetpidev** [comment]
@Soujanya2004 Please requested to review PR properly..

**Comment by Soujanya2004** [comment]
@Meetpidev fixed check now
