### ISSUE TITLE
[Feature Request]: add visitor count

### ISSUE THREAD

**Issue by Riyachauhan11** [Soujanya2004/wanderlust-2024#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add visitor count that would display how many users are using the website in footer

### Use Case

.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
usecase?

**Comment by Riyachauhan11** [comment]
> usecase?

shows how many people are interested in website and if the visitor count is high, more people will be interested in using the website or relying on the services offered. It also helps plan for scaling, like increasing server capacity if traffic is high.
