### ISSUE TITLE
[Documentation Update]: NO NEEED FOR BUTTON.

### ISSUE THREAD

**Issue by Meetpidev** [Soujanya2004/wanderlust-2024#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

DONT NEED "SHOW DETAILS" BTN AS WE CAN SEE THE DETAILS BY CLICKING CARD AT ANYWHERE..

![image](https://github.com/user-attachments/assets/8cbb28b0-1755-4776-9efa-69c54bc4eb2f)

### Suggested Change

SHOULD REMOVE IT

### Rationale

BETTER CARD UI..

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Meetpidev other contributor is working on it
