### ISSUE TITLE
[Bug]: improve style for top property page

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

change spelling of top properties
listing card not aligned properly
text in dark mode not visible on card name price and on heading

### Expected behavior

change style accordingly

### Add ScreenShots

![Screenshot (280)](https://github.com/user-attachments/assets/650b5b7d-4e56-4264-ad10-f05684ea27ae)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
there are 3 changes mentioned plz do all 3

**Comment by Meetpidev** [comment]
@Soujanya2004 Het you gave level 1 of this PR.. of that include solution for it..  please give it level 2 as you gave level 2 so thats why..
