### ISSUE TITLE
Improvement of flash message.

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#56]
**Problem**
For now the flash message is displaying using bootstrap simple alert message. Particularly for this there is an ISSUE, that is it's not automatically disappeared, need to manually close it or simply refresh the page for closing this, and it's directly placed in webpage as content which is very annoying and directly effect to the UX.
And also the flash message displaying very largely at the top of the screen with big size. That effect the UI of the Web site.
The Issue is here --->

https://github.com/user-attachments/assets/0b29caa7-7ca0-44a3-81b0-5368f34bb2a3

**Solution you'd like**
I want to replace this flash message with Bootstrap Toasts. For this the advantage is, it disappeared automatically after 5 second, You can also close it by clicking the cross button on it, which is impact the User Experience directly because it's not directly placed on the website content, Just appeared on the screen corner and disappeared automatically, like normal modern website looks like.
Like this -->

https://github.com/user-attachments/assets/d3b77738-8530-46e2-94af-006c8f8b46bb

Please assign me this ISSUE, I want to add this features Improvement.

**Comment by Soujanya2004** [comment]
@Suvadip-sana i wanted you to display error message in more creative ways, like " oops! looks like you have entered wrong password " or smtg like that, error msg has to be displayed on top itself
can you do that

**Comment by Suvadip-sana** [comment]
I am not talking about error message. I am old about flash message, which flash the message just one time after its occuring.
I think you also try to say the same.
If it's that then yes. I am capable to do this. just messages need to update. 

Is the flash message displaying format is left remain same or change it as I said earlier?

Please clarify this. @Soujanya2004

**Comment by Suvadip-sana** [comment]
If you assign me this task. Please give it label because it's need lot more work to update all type of message and also implement the Toasts flash. @Soujanya2004 


Thank You.

**Comment by Suvadip-sana** [comment]
@Soujanya2004 please clarify this.

**Comment by Soujanya2004** [comment]
@Suvadip-sana here you go

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
It's ready.
Should I create a PR? I also change the messages as you said.

https://github.com/user-attachments/assets/ac915c5b-ccce-40a4-8715-8dcfcf428a49
