### ISSUE TITLE
Add eye symbol to see the password  in sign up and login page

### ISSUE THREAD

**Issue by lakshmirajvagu** [Soujanya2004/wanderlust-2024#59]
When we want to see the password in sign in and login page i will add eye symbol so that password can be seen by us 
![Screenshot 2024-10-09 181138](https://github.com/user-attachments/assets/72005386-defa-4adf-b54e-1e068c24939f)

**Comment by geetanjalidubey9** [comment]
pls assign this task to me

**Comment by raj-adi00** [comment]
I can do this is this issue open

**Comment by Soujanya2004** [comment]
@raj-adi00 confirm password feature is already implemented, first pull the code and work on the issue

**Comment by raj-adi00** [comment]
Thank you for assigning please add label Hacktoberfest

**Comment by Soujanya2004** [comment]
@raj-adi00 its not under hactoberfest

**Comment by raj-adi00** [comment]
@Soujanya2004 Raise a PR. Please Review that
