### ISSUE TITLE
proposing an  filter/sort functionality for services based on user choices

### ISSUE THREAD

**Issue by ROHAN7051** [Soujanya2004/wanderlust-2024#6]
i would like to work on enchancing the functionality of the website by adding an filter/sort function and more optimization of the site

**Comment by krishkishore972** [comment]
hey i want to work on this issue assign me this ive done this project earlier

**Comment by Soujanya2004** [comment]
@krishkishore972 progress?

**Comment by AnsharaFayazBeigh** [comment]
Hi ! @Soujanya2004 
I prppose the  following for this existing  issue.
**Implement Filter/Sort Functionality for Services,**
’d like to propose adding a filter and sort functionality for our services to enhance the user experience. This feature will allow users to filter services based on categories such as trending, surfing, amazing cities, beaches, farms, lakes, castles, rooms, forests, and pools. Additionally, users should be able to sort the services by price or rating.


UI Components: Create a filter sidebar and sorting dropdown for the various categories.
Frontend Logic: Implement JavaScript to update displayed services based on user choices.
I’d love to take this on myself, so please don’t assign it to anyone else for now.
I believe this will be a valuable Level 3 contribution.
Thank  you!

**Comment by Soujanya2004** [comment]
@AnsharaFayazBeigh you can create ur own token in the official website
if u encounter an issue with that i will give u the token send me ur contact details

**Comment by Soujanya2004** [comment]
@AnsharaFayazBeigh issue solved
thanks for the interest
