### ISSUE TITLE
Addition of pages/links to items 

### ISSUE THREAD

**Issue by Shirisha-16** [Soujanya2004/wanderlust-2024#61]
Want to links to navigate to different pages showing collections 
![Screenshot 2024-10-10 004455](https://github.com/user-attachments/assets/6bf440f3-4aab-41c8-8df8-6153efc66ea8)
I want to work on this issue
@Soujanya2004 assign me this task with labels gssoc-ext,hacktoberfest-accepted and level according to issue

**Comment by Soujanya2004** [comment]
@Shirisha-16 here you go
