### ISSUE TITLE
[Feature Request]: Adding a Favorites Section in the Navbar.

### ISSUE THREAD

**Issue by darshinihoney** [Soujanya2004/wanderlust-2024#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A heart or bookmark icon prominently displayed in the navbar, making it easily accessible from any page.

### Use Case

Users can explore various destinations and experiences but often aren’t ready to book immediately. 
Without a feature to save or mark their favorites, they may lose track of their interests.

### Benefits

Users can quickly find and revisit items they liked without having to search through the entire site again.

### Add ScreenShots

![Screenshot 2024-10-10 233910](https://github.com/user-attachments/assets/3f0ccb97-e46a-4819-aaf2-ca0f55744b96)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@darshinihoney here you go

**Comment by Soujanya2004** [comment]
@darshinihoney progress?

**Comment by darshinihoney** [comment]
@Soujanya2004 Max today night I'll keep pr

**Comment by Soujanya2004** [comment]
@darshinihoney sure

**Comment by Soujanya2004** [comment]
@harshbhar0629

**Comment by harshbhar0629** [comment]
@Soujanya2004 Please assign to me
