### ISSUE TITLE
[Documentation Update]: Readme update visually appealing

### ISSUE THREAD

**Issue by eshalshaikh07** [Soujanya2004/wanderlust-2024#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Hi,

I hope this message finds you well. I’m eager to contribute to the project and would love to take on the task of enhancing the README. I have already successfully completed one README task, where I made it more interactive and visually appealing by adding GIFs to demonstrate key features.

Please let me know if you can assign this task to me. I’m looking forward to your feedback and am excited to contribute further!

Thank you!

Best regards,
Eshal :)

### Suggested Change

Adding iimages,graphics,gifs

### Rationale

A visually appealing README is crucial because it serves as the first impression of the project. It enhances user engagement, making it easier for newcomers to understand the project's purpose and functionalities. By incorporating visual elements like GIFs and diagrams, we can simplify complex concepts, provide clear instructions, and ultimately encourage more users to explore and contribute to the project.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@eshalshaikh07 here you go

**Comment by anchalchaturvedi08** [comment]
Can I work on this issue?
