### ISSUE TITLE
[Documentation Update]: Update README for Enhanced Appeal and Contributor Section

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Soujanya2004/wanderlust-2024#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Propose to enhance the README file by making it more engaging and visually appealing. Additionally, include a contributor section similar to the one in the provided image to acknowledge the contributors effectively.

![image](https://github.com/user-attachments/assets/6b6394b9-a2d0-4526-ad9a-ac2c33efe46b)

### Suggested Change

Enhance the README by adding a detailed description of the project, its purpose, and key features. Include a contributors section to recognize participants and make the documentation more engaging and informative.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AnushkaChouhan25** [comment]
Please also assign this under hactoberfest and hactoberfest-accepted. Thank you!

**Comment by Soujanya2004** [comment]
@AnushkaChouhan25 its not under hactoberfest
