### ISSUE TITLE
[Bug]: Cards is not responsive in the home page

### ISSUE THREAD

**Issue by Hemraj-7** [Soujanya2004/wanderlust-2024#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In our website cards is not responsive. these card not showing proper in the small devices like phone

### Expected behavior

In our website cards is not responsive. these card not showing proper in the small devices like phone

### Add ScreenShots

![Screenshot 2024-10-14 154715](https://github.com/user-attachments/assets/33adf743-9ea8-4549-beae-75c741d5ef68)

### On which device are you experiencing this bug?

- Mobile phone

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Hemraj-7** [comment]
I want to do this work.
Assign me

**Comment by hemanthijjurouthu** [comment]
"Ma'am, I would like to take the initiative to work on this issue. Could you kindly assign it to me? I’m confident that I can contribute effectively and would appreciate the opportunity."

**Comment by Soujanya2004** [comment]
@hemanthijjurouthu here you go
