### ISSUE TITLE
[Feature Request]: Password Recovery Feature

### ISSUE THREAD

**Issue by saras-69** [Soujanya2004/wanderlust-2024#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The password recovery feature allows users to reset their passwords securely if they forget them. This enhancement will involve creating a user-friendly interface where users can request a password reset link to their registered email addresses.

### Use Case

This feature will enhance user experience by providing a simple and efficient way for users to regain access to their accounts without requiring direct support intervention. For example, if a user forgets their password, they can easily request a reset link, enabling them to reset their password and regain access quickly.

### Benefits

Implementing this feature will:

Improve user experience by minimizing downtime due to forgotten passwords.
Reduce the workload on support teams by allowing users to handle password resets independently.
Enhance overall security by using secure password recovery processes (e.g., email verification).

### Add ScreenShots

![Screenshot 2024-10-15 022439](https://github.com/user-attachments/assets/901b6be6-ecc2-45fb-807e-4926fa94a3ee)
![Screenshot 2024-10-13 235803](https://github.com/user-attachments/assets/b9318f05-90ff-4db3-8b65-90b73c8d67f2)
![Screenshot 2024-10-13 024658](https://github.com/user-attachments/assets/c518ddf4-d260-4f9e-aaf7-332592d147c2)

https://github.com/user-attachments/assets/2b3f89b6-3ead-44b0-8265-6ea19e3ce13b

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@saras-69 here you go

**Comment by NK-Works** [comment]
@Soujanya2004 I see no PRs and its been three weeks. I can work on this issue...
Can you assign me

**Comment by Soujanya2004** [comment]
@saras-69 there is no updates since 3 weeks so 8 will assign this to others

**Comment by harshbhar0629** [comment]
Please assign to me

**Comment by saras-69** [comment]
@Soujanya2004 "Apologies for the delay. I’ll make sure to have updates for you by Sunday."

**Comment by Soujanya2004** [comment]
@harshbhar0629 progress?

**Comment by Soujanya2004** [comment]
guys i will merge whoever raises the pr first
