### ISSUE TITLE
[Bug]: Cannot add new reviews

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After a user login or signup then adds a review, it is not updated 
404 page not found is seen

### Expected behavior

review should be added as a user tries to add a new one 

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
I have identified this issue and would like to work on it. I have experience in debugging similar problems. Could you please assign this issue to me and add the Hacktoberfest labels? Thank you!

**Comment by Soujanya2004** [comment]
@dipexplorer
And this is not under hactokerfest, GSSoC project only , would you like to work on it

**Comment by dipexplorer** [comment]
Yes please assign it.
