### ISSUE TITLE
[Bug]: Not able to add new listing 

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

after clicking 'airbnb ur home' user is not able to add new listing
error: Failed to load listing details! 

### Expected behavior

able to upload new listings like before

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dipexplorer** [comment]
I have experience in similar problems. Could you please assign this issue to me ? Thank you!
