### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Vaishh18** [Soujanya2004/wanderlust-2024#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No privacy-policy page and terms page for the links in the footer 

https://github.com/user-attachments/assets/b596f3c7-b70a-47a0-ba1b-47074111ed23

### Expected behavior

There should be privacy-policy page and terms page

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@Vaishh18 the issue is solved
